// Markdown brief for a single company playbook — the "Copy for LLM" payload that lets a dev paste a
// playbook into Claude Code and have it applied to the current repo (Direction #3 + the #6 reuse).
// Pure + client-safe (no server imports), so the PlaybooksPanel can build it inline.

/** Fields both artifacts consume. Callers pass PlaybookRow (including `version`). */
type PlaybookBriefSource = {
  title: string;
  dimId: string;
  summary: string;
  steps: string[];
  version: number;
};

export function playbookMarkdown(p: PlaybookBriefSource, dimLabel: string): string {
  const out: string[] = [];
  out.push(`# Apply playbook: ${p.title}`);
  // Same `v{n}` pin as playbookStarterFile's blockquote — PR body and committed file name one revision.
  out.push(`Strengthens ${p.dimId} (${dimLabel}) v${p.version}.`);
  if (p.summary) {
    out.push("");
    out.push(p.summary);
  }
  if (p.steps.length) {
    out.push("");
    out.push("## Steps");
    for (const s of p.steps) out.push(`- ${s}`);
  }
  out.push("");
  out.push("## Ask");
  out.push(
    "Apply this playbook to the current repository: implement the steps above as concrete changes, then open a pull request. Call out any step that doesn't apply here and why.",
  );
  return out.join("\n");
}

/**
 * The exact `docs/playbooks/<slug>.md` starter file the apply route commits when rolling a playbook
 * into a repo (PRAC-5) — a leak-free, org-authored "practice with a starter". Single-sourced here so
 * the apply route, apply-batch `dryRun: true` (`starter` in the preview payload), and the
 * PlaybookCard "Preview starter" render the identical artifact. Pure + client-safe. The opening
 * blockquote pins `v{PlaybookRow.version}` so a later edit is visible in the committed file, not
 * only on the Ascent card.
 */
export function playbookStarterFile(p: PlaybookBriefSource, dimLabel: string): string {
  const stepsChecklist = p.steps.length
    ? p.steps.map((s) => `- [ ] ${s}`).join("\n")
    : "- [ ] <!-- TODO: break this playbook into concrete steps for this repo -->";
  return `# Playbook: ${p.title}

> Org standard for **${p.dimId} · ${dimLabel}** v${p.version}, rolled out from Ascent. Track adoption by
> completing the steps below, then mark this PR ready for review.

${p.summary ? `${p.summary}\n\n` : ""}## Steps
${stepsChecklist}

---
Generated by Ascent, your AI-native maturity companion.
`;
}

/**
 * HITL preview for fleet apply-batch (`dryRun: true`): the exact starter file bytes that would
 * be committed, plus the capped unique repo list. Pure — no GitHub, no token. The apply-batch
 * route returns this before `requirePrWriteContext`, so a preview cannot mint a token or open a
 * PR. The route still requires admin on the playbook's org; starter bytes are not public.
 */
export function playbookApplyBatchDryRun(
  playbook: PlaybookBriefSource,
  dimLabel: string,
  repos: readonly string[],
  skipped: number,
): { repos: string[]; starter: string; skipped: number } {
  return {
    repos: [...repos],
    starter: playbookStarterFile(playbook, dimLabel),
    skipped,
  };
}
