import { describe, it, expect } from "vitest";
import { playbookMarkdown, playbookStarterFile } from "./playbook-brief";

describe("playbookMarkdown", () => {
  it("renders title, dimension, summary, steps and an apply ASK", () => {
    const md = playbookMarkdown(
      { title: "Our CI standard", dimId: "D5", summary: "Required checks on every PR.", steps: ["lint", "test", "build"] },
      "CI/CD",
    );
    expect(md).toContain("# Apply playbook: Our CI standard");
    expect(md).toContain("Strengthens D5 (CI/CD).");
    expect(md).toContain("Required checks on every PR.");
    expect(md).toContain("## Steps");
    expect(md).toContain("- lint");
    expect(md).toContain("## Ask");
    expect(md).toMatch(/open a pull request/);
  });

  it("omits the summary and steps sections when empty", () => {
    const md = playbookMarkdown({ title: "T", dimId: "D1", summary: "", steps: [] }, "Foundations");
    expect(md).not.toContain("## Steps");
    expect(md).toContain("## Ask");
  });
});

// playbookStarterFile produces the exact `docs/playbooks/<slug>.md` body the apply route commits
// into a customer's repo (apply/route.ts:67,79) AND the PlaybookCard "Preview starter" renders
// (PlaybookCard.tsx:153). The two MUST be byte-identical, so these tests pin the literal artifact —
// a regression here silently changes what gets written into customer PRs.
describe("playbookStarterFile", () => {
  it("pins the EXACT committed artifact body for a representative playbook (path + content)", () => {
    const file = playbookStarterFile(
      { title: "Our CI standard", dimId: "D5", summary: "Required checks on every PR.", steps: ["lint", "test", "build"] },
      "CI/CD",
    );
    // Exact-artifact invariant: the generated file content is byte-for-byte the documented template.
    // Pinned as a literal so any change to path-implied slug body, heading, fallback or footer fails loudly.
    const expected = `# Playbook: Our CI standard

> Org standard for **D5 · CI/CD**, rolled out from Ascent. Track adoption by
> completing the steps below, then mark this PR ready for review.

Required checks on every PR.

## Steps
- [ ] lint
- [ ] test
- [ ] build

---
Generated by Ascent — your AI-native maturity companion.
`;
    expect(file).toBe(expected);
    // The committed path is `docs/playbooks/<slug>.md`; the body's H1 is the human title that pairs with it.
    expect(file.startsWith("# Playbook: Our CI standard\n")).toBe(true);
    // Footer terminator is always present and the file ends with a single trailing newline.
    expect(file.endsWith("Generated by Ascent — your AI-native maturity companion.\n")).toBe(true);
  });

  it("renders steps as a GitHub task-list checklist (one unchecked box per step)", () => {
    const file = playbookStarterFile(
      { title: "T", dimId: "D1", summary: "", steps: ["alpha", "beta"] },
      "Foundations",
    );
    expect(file).toContain("## Steps\n- [ ] alpha\n- [ ] beta\n");
    // Exactly one checkbox per step — no extra/dropped lines.
    expect(file.match(/- \[ \] /g)).toHaveLength(2);
  });

  it("emits the documented TODO fallback (not an empty/malformed file) when there are no steps", () => {
    const file = playbookStarterFile(
      { title: "Empty playbook", dimId: "D2", summary: "", steps: [] },
      "Delivery",
    );
    const expected = `# Playbook: Empty playbook

> Org standard for **D2 · Delivery**, rolled out from Ascent. Track adoption by
> completing the steps below, then mark this PR ready for review.

## Steps
- [ ] <!-- TODO: break this playbook into concrete steps for this repo -->

---
Generated by Ascent — your AI-native maturity companion.
`;
    expect(file).toBe(expected);
    // The ## Steps section is never empty — fallback keeps the markdown well-formed.
    expect(file).toContain("## Steps\n- [ ]");
  });

  it("omits the summary block when summary is empty (no stray blank lines)", () => {
    const file = playbookStarterFile(
      { title: "T", dimId: "D1", summary: "", steps: ["x"] },
      "Foundations",
    );
    // No summary => the blockquote is immediately followed by the Steps heading.
    expect(file).toContain("then mark this PR ready for review.\n\n## Steps");
    expect(file).not.toContain("\n\n\n## Steps");
  });

  it("includes the summary block verbatim when present", () => {
    const file = playbookStarterFile(
      { title: "T", dimId: "D1", summary: "Multi\nline summary.", steps: ["x"] },
      "Foundations",
    );
    expect(file).toContain("\nMulti\nline summary.\n\n## Steps\n");
  });

  it("renders special-chars / markdown-ish input safely (no broken structure, no injection)", () => {
    const file = playbookStarterFile(
      {
        title: "Edge `case` & <stuff>",
        dimId: "D3",
        summary: "Has *markdown* and `backticks` & <html>.",
        steps: ["step with `code`", "step with --- dashes", "step with #hash and [link](x)"],
      },
      "Security & Compliance",
    );
    // Content is passed through literally (markdown is the intended format) and structurally intact:
    // the footer fence and heading survive regardless of special chars in user-controlled fields.
    expect(file).toContain("# Playbook: Edge `case` & <stuff>");
    expect(file).toContain("**D3 · Security & Compliance**");
    expect(file).toContain("- [ ] step with `code`");
    expect(file).toContain("- [ ] step with --- dashes");
    expect(file).toContain("- [ ] step with #hash and [link](x)");
    // The closing `---` + footer line is always the last structural element.
    expect(file.trimEnd().endsWith("Generated by Ascent — your AI-native maturity companion.")).toBe(true);
    expect(file.split("\n---\nGenerated by Ascent")).toHaveLength(2);
  });
});
