// The promotion BRIDGE between Ascent's two skill systems: the per-repo GENERATED onboarding skill
// (src/lib/onboarding — a scan rendered into a SKILL.md the repo runs locally) and the org SKILLS
// LIBRARY (src/lib/db/org-skills.ts — curated, versioned, synced entries). Until now a generated skill
// could only be downloaded; promoting it turns a one-off export into a library entry the whole org can
// find, adopt, sync and track.
//
// Pure string/shape work (the report is the only input, no I/O) so the route stays a thin auth+persist
// shell and the interesting logic is unit-testable without HTTP.

import { buildOnboardingSkill, type SelectOpts } from "@/lib/onboarding";
import type { ScanReport } from "@/lib/types";
import type { SkillCategory } from "@/lib/org/skill-categories";
import { ensureFrontmatter, parseSkillFrontmatter, slugifySkillName } from "@/lib/org/skill-frontmatter";

/** A generated onboarding skill is, by definition, an AI-native practice — the library category. */
export const PROMOTED_SKILL_CATEGORY: SkillCategory = "ai-native";

export interface PromotedSkill {
  /** kebab-case slug, derived from the repo — one library entry per repo, so a re-promote is an update. */
  name: string;
  description: string;
  category: SkillCategory;
  tags: string[];
  /** Full SKILL.md with a contract-valid frontmatter block. */
  content: string;
  /** The practice/track ids the generator selected (audit + "what's in this skill"). */
  trackIds: string[];
}

/**
 * The library name for a promoted repo skill: `ascent-onboard-<owner>-<repo>`. Repo-derived (not the
 * generator's fixed `ascent-onboard`) so two repos promoted into the same org don't collide — and so a
 * re-promote of the SAME repo lands on the same name (the 409 the route reports).
 */
export function promotedSkillName(owner: string, repo: string): string {
  return slugifySkillName(`ascent-onboard-${owner}-${repo}`);
}

/** Fallback description when the generated block doesn't supply one (kept to a single line). */
export function promotedSkillDescription(report: ScanReport): string {
  const repo = `${report.repo.owner}/${report.repo.name}`;
  return (
    `Personalized AI-native onboarding for ${repo}, generated by Ascent from the ` +
    `${report.scannedAt.slice(0, 10)} scan (${report.level.id} ${report.level.name}, ` +
    `${report.overallScore}/100). Run it to adopt the highest-leverage practices for this repo.`
  );
}

/**
 * Build the library entry for a repo's generated onboarding skill: take the generator's SKILL.md, keep
 * its description (it already states when to use the skill), and RE-WRAP the body with a contract-valid
 * block carrying the repo-derived name + the ai-native category. The generator's own `name:`
 * (`ascent-onboard`, identical for every repo) is deliberately replaced — inside the library a name is
 * an identity, not a slash-command.
 */
export function buildPromotedSkill(report: ScanReport, opts?: SelectOpts): PromotedSkill {
  const generated = opts ? buildOnboardingSkill(report, opts) : buildOnboardingSkill(report);
  const parsed = parseSkillFrontmatter(generated.body);
  const declared = (parsed.raw.description ?? "").trim();
  const description = declared || promotedSkillDescription(report);
  const name = promotedSkillName(report.repo.owner, report.repo.name);
  const tags = [
    "ascent",
    "onboarding",
    report.repo.owner.toLowerCase(),
    ...generated.trackIds.map((t) => t.toLowerCase()),
  ].slice(0, 20);
  // Wrap the BODY (block stripped) so the generator's fixed name can't survive into the library entry.
  const content = ensureFrontmatter(parsed.body, {
    name,
    description,
    category: PROMOTED_SKILL_CATEGORY,
    tags,
  });
  return { name, description, category: PROMOTED_SKILL_CATEGORY, tags, content, trackIds: generated.trackIds };
}
