// Registry technique vocabulary for the authored interactive studies.
export const SURFACE_STUDIES: Readonly<Record<string, readonly string[]>> = {
  motion: [
    "gesture-decomposition",
    "preset-vocabulary",
    "engine-selection",
    "performance-discipline",
    "taste-budgets",
    "one-shot-guarding",
    "reduced-motion-mechanics",
    "content-bearing-degradation",
    "unprompted-motion-lifecycle",
    "loop-pause-governance",
  ],
  accessibility: [
    "primitive-level-a11y",
    "keyboard-navigation-models",
    "hidden-but-mounted-inertness",
    "live-region-architecture",
    "name-and-description-wiring",
    "preference-respect",
    "a11y-verification",
    "assistive-tech-divergence",
  ],
  "adaptive-fidelity-tiers": [
    "measured-not-declared-capability",
    "asymmetric-tier-transitions",
    "measurement-settle-budget",
    "probe-deferral-to-idle",
    "per-tier-budget-tables",
    "preference-short-circuits-measurement",
  ],
  "async-ui-states": [
    "state-model",
    "placeholder-design",
    "action-busy-states",
    "empty-state-design",
    "failure-states",
    "arrival-choreography",
    "windowing-vs-identifying-keys",
  ],
  "design-tokens": [
    "token-taxonomy",
    "theme-architecture",
    "cross-language-token-parity",
    "token-enforcement",
    "motion-tokens",
    "density-and-scale-axes",
  ],
  "status-vocabulary": [
    "vocabulary-chain-integrity",
    "status-color-mapping",
    "number-formatting",
    "timestamp-display",
    "untrusted-label-rendering",
    "vocabulary-evolution-checklist",
  ],
  "toasts-notifications": [
    "severity-taxonomy",
    "queue-discipline",
    "actionable-toasts",
    "durable-notification-ledger",
    "os-escalation",
    "announcement-accessibility",
  ],
  "canvas-graph": [
    "viewport-transform",
    "render-budget",
    "direct-manipulation",
    "graph-layout",
    "edge-management",
    "canvas-accessibility",
  ],
  "data-viz": [
    "metric-identity",
    "scale-and-axis-design",
    "chart-loading-economics",
    "micro-visualizations",
    "encoding-vocabulary",
    "empty-and-degraded-chart-states",
  ],
  "diff-comparison": [
    "pair-and-baseline-selection",
    "semantic-level-selection",
    "computation-offload",
    "presentation-modes",
    "drift-against-declared",
    "diff-honesty",
    "invisible-differences",
  ],
  feed: [
    "reverse-chronology-semantics",
    "live-prepend",
    "event-clustering",
    "read-position-and-unseen",
    "feed-retention",
  ],
  "file-browsing": [
    "listing-and-refresh",
    "navigation-state",
    "selection-model",
    "file-mutations",
    "thumbnails-and-previews",
    "kind-taxonomy",
  ],
  search: [
    "query-parsing",
    "full-text-indexing",
    "ranking-and-excerpts",
    "faceting-and-filters",
    "saved-views",
    "command-surface",
    "typed-filter-language",
  ],
  table: ["pagination", "sorting", "performance", "loading-and-empty-states", "client-server-split"],
};
