// The exemplar section of the LLM briefing (moonshot #34), and the byte-stability guarantee that
// lets it be added at all.
//
// `src/app/api/report/llm/route.test.ts` asserts the endpoint's body IS `reportLlmMarkdown(report)`,
// and ReportHeader.test.tsx asserts the copy chip's payload is the same string. Neither file is
// touched by this lane, so the new argument MUST be inert when absent — the first test below is what
// pins that. FAIL-BEFORE: push the section unconditionally (drop the `if (options.exemplarSection)`)
// and it goes red, as does the untouched route test.

import { describe, it, expect } from "vitest";
import { exemplarMarkdownSection, reportLlmMarkdown } from "./llm-markdown";
import { diffAcrossRepos, transferJoin, type ExemplarProfile } from "./exemplar";
import type { ComparableDimension, ComparableScan } from "@/lib/db/scans";
import type { MinedPractice } from "@/lib/org/practice-mining";
import type { ScanReport } from "@/lib/types";

function report(): ScanReport {
  return {
    repo: { owner: "acme", name: "api", url: "https://github.com/acme/api", stars: 1, forks: 0, defaultBranch: "main", headSha: null, primaryLanguage: "TypeScript" },
    overallScore: 61,
    adoptionScore: 55,
    rigorScore: 66,
    level: { id: "L3", name: "Established", band: [55, 70], blurb: "" },
    posture: { id: "balanced", name: "Balanced", blurb: "" },
    archetype: "team",
    confidence: 0.8,
    scannedAt: "2026-08-01T00:00:00.000Z",
    headline: "A team repo mid-transition.",
    summary: "",
    strengths: ["CI is enforced"],
    risks: ["Coverage is unmeasured"],
    dimensions: [
      { id: "D2", name: "Testing", score: 40, weight: 0.2, summary: "Thin", evidence: [], gaps: ["No coverage gate"] },
    ],
    roadmap: [{ title: "Add a coverage gate", dimension: "D2", impact: "high", effort: "medium", rationale: "", explore: [] }],
    engine: { provider: "claude-cli", model: "sonnet", rubricVersion: "r10" },
    warnings: [],
  } as unknown as ScanReport;
}

function dim(dimId: string, o: { score?: number; evidence?: string[] } = {}): ComparableDimension {
  return { dimId, name: dimId === "D2" ? "Testing" : `${dimId} name`, score: o.score ?? 50, signalScore: o.score ?? 50, evidence: o.evidence ?? [], gaps: [] };
}

function subject(dimensions: ComparableDimension[]): ComparableScan {
  return {
    id: "s1", scannedAt: "2026-08-01T00:00:00.000Z", overallScore: 61, level: "L3", levelName: "Established",
    archetype: "team", adoptionScore: 55, rigorScore: 66, posture: "balanced", confidence: 0.8,
    engineProvider: "claude-cli", engineModel: "sonnet", headSha: null, dimensions, recommendations: [],
  };
}

function profile(dimensions: ComparableDimension[], over: Partial<ExemplarProfile> = {}): ExemplarProfile {
  return {
    key: "repo:acme/web", kind: "repo", label: "acme/web", repoFullName: "acme/web",
    scannedAt: "2026-08-02T00:00:00.000Z", overallScore: 75, dimensions, population: null,
    basis: { rubric: "r10", excludesMockEngine: true, minSupport: null },
    ...over,
  };
}


// The PRE-CHANGE bytes, captured by running the generator on the commit before this lane touched it.
// Comparing reportLlmMarkdown(r) against reportLlmMarkdown(r, {}) is NOT enough on its own: both go
// through the same code, so an unconditional `out.push(section ?? "")` shifts them together and the
// equality still holds (verified — that variant left the route test green too). Only a frozen fixture
// catches a stray blank line.
const PRE_CHANGE = "# Ascent maturity report: acme/api\n\nhttps://github.com/acme/api\n\n> **INCOMPLETE SCAN: do not treat the score as a measurement.** No dimension could be scored (every detector failed or returned no data), so the overall score and level are the renormalized floor, not a verdict on this repository. Re-scan or check repository access.\n\n**Overall 61/100 \u00b7 L3 Established** \u00b7 adoption 55 \u00b7 rigor 66\n\n- scanned: 2026-08-01T00:00:00.000Z\n- archetype: team\n- posture: balanced\n- confidence: 80%\n- engine: claude-cli / sonnet\n- rubric: r10\n\n## Roadmap\n\n1. **Add a coverage gate** \u00b7 D2 \u00b7 impact: high \u00b7 effort: medium\n\n## Ask\n\nThis scan produced no usable measurement. Do not plan work from the scores above; say so, and help diagnose why the scan could not read this repository.\n\n---\nGenerated by Ascent \u00b7 acme/api \u00b7 L3 Established \u00b7 61/100";

/** The exact report those bytes were generated from. */
function fixtureReport(): ScanReport {
  return {
    repo: { owner: "acme", name: "api", url: "https://github.com/acme/api", stars: 1, forks: 0, defaultBranch: "main", headSha: null, primaryLanguage: null },
    overallScore: 61, adoptionScore: 55, rigorScore: 66,
    level: { id: "L3", name: "Established", band: [55, 70], blurb: "" },
    posture: { id: "balanced", name: "Balanced", blurb: "" },
    archetype: "team", confidence: 0.8, scannedAt: "2026-08-01T00:00:00.000Z",
    headline: "", summary: "", strengths: [], risks: [], dimensions: [],
    roadmap: [{ title: "Add a coverage gate", dimension: "D2", impact: "high", effort: "medium", rationale: "", explore: [] }],
    engine: { provider: "claude-cli", model: "sonnet", rubricVersion: "r10" }, warnings: [],
  } as unknown as ScanReport;
}

describe("reportLlmMarkdown byte-stability", () => {
  it("is byte-identical with the option absent, with {}, and with an explicitly null section", () => {
    const r = report();
    const base = reportLlmMarkdown(r);
    expect(reportLlmMarkdown(r, {})).toBe(base);
    expect(reportLlmMarkdown(r, { exemplarSection: null })).toBe(base);
    expect(reportLlmMarkdown(r, { exemplarSection: "" })).toBe(base);
    expect(base).not.toContain("Against exemplar");
  });

  // FAIL-BEFORE: replace the `if (options.exemplarSection)` guard with an unconditional
  // `out.push(options.exemplarSection ?? "")` and this goes red on two stray newlines.
  it("matches the pre-change bytes exactly", () => {
    expect(reportLlmMarkdown(fixtureReport())).toBe(PRE_CHANGE);
    expect(reportLlmMarkdown(fixtureReport(), {})).toBe(PRE_CHANGE);
  });

  it("lands the section immediately BEFORE '## Ask' when one is supplied", () => {
    const out = reportLlmMarkdown(report(), { exemplarSection: "## Against exemplar\n\nbody" });
    expect(out.indexOf("## Against exemplar")).toBeGreaterThan(out.indexOf("## Roadmap"));
    expect(out.indexOf("## Against exemplar")).toBeLessThan(out.indexOf("## Ask"));
  });
});

describe("exemplarMarkdownSection", () => {
  const diff = diffAcrossRepos(
    subject([dim("D2", { score: 40, evidence: ["Found 6 test files"] }), dim("D5", { score: 50 })]),
    profile([dim("D2", { score: 54, evidence: ["found 6 TEST files", "Coverage tracking configured"] })]),
  );

  it("leads with the basis and the signal-level caveat, then the absent signals", () => {
    const md = exemplarMarkdownSection({ diff });
    expect(md.startsWith("## Against exemplar")).toBe(true);
    expect(md).toContain("rubric: r10");
    expect(md).toContain("mock-engine scans excluded");
    expect(md).toContain("Signal-level, not semantic");
    expect(md).toContain("### D2 · Testing (+14)");
    expect(md).toContain("- Coverage tracking configured");
    // A one-sided dimension is named as not comparable rather than counted as a gap.
    expect(md).toContain("Not comparable (scored on only one side, so no gap is claimed): D5.");
  });

  it("names the practice that transfers the signals when one is joined in", () => {
    const mined: MinedPractice[] = [];
    const md = exemplarMarkdownSection({ diff, transfers: transferJoin(diff, mined, "acme") });
    expect(md).toContain("_transfers via:_ Test discipline");
  });

  it("NEVER names a repo for a cohort brief", () => {
    const cohortDiff = diffAcrossRepos(
      subject([dim("D2", { score: 40 })]),
      profile([dim("D2", { score: 70, evidence: ["SAST in CI"] })], {
        kind: "cohort",
        key: "cohort:lang:TypeScript",
        label: "TypeScript · top decile",
        repoFullName: null,
        scannedAt: null,
        population: 42,
        basis: { rubric: "r10", excludesMockEngine: true, minSupport: 4 },
      }),
    );
    const md = exemplarMarkdownSection({ diff: cohortDiff });
    expect(md).toContain("TypeScript · top decile");
    expect(md).toContain("cohort population: 42");
    expect(md).toContain("signal support: 4 of the top decile");
    expect(md).not.toMatch(/[\w.-]+\/[\w.-]+/);
  });

  it("says so plainly when there is nothing to transfer", () => {
    const flat = diffAcrossRepos(subject([dim("D2", { evidence: ["x"] })]), profile([dim("D2", { evidence: ["X"] })]));
    expect(exemplarMarkdownSection({ diff: flat })).toContain("Nothing this exemplar has is missing here.");
  });

  it("states an ineligible subject in the basis instead of hiding the mismatch", () => {
    const d = diffAcrossRepos(subject([dim("D2")]), profile([dim("D2")]), { subjectEligible: false });
    expect(exemplarMarkdownSection({ diff: d })).toContain("measured differently");
  });
});
