export { getPrisma, isDbConfigured } from "@/lib/db/client";
export {
  persistScanReport,
  findScanByCommit,
  getHeadHint,
  getRepositoryHistory,
  getScanComparison,
  getScanReportByCommit,
  getLatestRecommendations,
  updateRecommendationStatus,
  recordAudit,
  getAuditLog,
  getPublicScanGallery,
  reportPermalink,
  type PersistResult,
  type RepositoryHistory,
  type HistoryPoint,
  type ScanComparison,
  type ComparableScan,
  type ComparableDimension,
  type ComparableRecommendation,
  type PublicRepoCard,
  type PublicScanGallery,
  type AuditLogEntry,
  type AuditLogPage,
  type AuditLogQuery,
  type AuditScanRef,
} from "@/lib/db/scans";
export {
  purgeExpiredData,
  envRetentionDefaults,
  resolveRetention,
  clampBatchSize,
  PURGE_ACTION,
  RETENTION_DEFAULT_BATCH_SIZE,
  type RetentionPolicy,
  type OrgPurgeResult,
  type PurgeSummary,
} from "@/lib/db/retention";
export { getUsageSummary, type UsageSummary, type ProviderUsage, type UsageDay } from "@/lib/db/usage";
export {
  upsertInstallation,
  removeInstallation,
  getInstallationIdForOwner,
} from "@/lib/db/installations";
export {
  setRepoWatch,
  setRepoSchedule,
  listWatchedRepos,
  getOrgRollup,
  getRepoStates,
  getOrgContributors,
  getContributorInsights,
  getOrgPrSignals,
  getOrgGovernance,
  getOrgActivity,
  getOrgPractices,
  getOrgGapAnalysis,
  getOrgMovers,
  getOrgRecommendations,
  getOrgDiscrepancies,
  getOrgBenchmark,
  listDueRescans,
  advanceSchedule,
  getOrgId,
  isRepoWatched,
  type DueRescan,
  type RepoRef,
  type OrgRepoRow,
  type OrgRollup,
  type RepoState,
  type OrgContributor,
  type ContributorInsight,
  type RepoConcentration,
  type ContributorInsights,
  type OrgPrSignals,
  type OrgGovernance,
  type RepoGovernance,
  type OrgActivity,
  type OrgPractice,
  type OrgGapAnalysis,
  type CommonGap,
  type RepoOutlier,
  type OrgMovers,
  type RepoMove,
  type OrgRec,
  type OrgBenchmark,
  type OrgDiscrepancies,
  type DiscrepancyGroup,
} from "@/lib/db/org";
export {
  createGoal,
  listGoals,
  updateGoal,
  deleteGoal,
  createInitiative,
  listInitiatives,
  updateInitiativeStatus,
  simulateOrgFix,
  isGoalMetric,
  metricLabel,
  type GoalProgress,
  type GoalMetric,
  type InitiativeRow,
} from "@/lib/db/plan";
export {
  forecastTrajectory,
  forecastHeadline,
  humanizeDays,
  type Forecast,
  type LevelEta,
  type Trajectory,
  type SeriesPoint,
} from "@/lib/maturity/forecast";
