export {
  getPrisma,
  isDbConfigured,
  withDb,
  withRetry,
  reconnectDb,
  dbHealthCheck,
  isAuthExpiryError,
  isSerializationConflictError,
  type RetryOptions,
} from "@/lib/db/client";
export {
  persistScanReport,
  findScanByCommit,
  getHeadHint,
  getRepositoryHistory,
  getScanComparison,
  getScanReportByCommit,
  getLatestRecommendations,
  updateRecommendation,
  updateRecommendationStatus,
  getRecommendationEvents,
  getRecommendationOrgSlug,
  recordAudit,
  getAuditLog,
  getPublicScanGallery,
  reportPermalink,
  type PersistResult,
  type RecommendationPatch,
  type RecommendationActor,
  type RepositoryHistory,
  type HistoryPoint,
  type ScanComparison,
  type ComparableScan,
  type ComparableDimension,
  type ComparableRecommendation,
  type PublicRepoCard,
  type PublicScanGallery,
  type AuditLogEntry,
  type AuditLogPage,
  type AuditLogQuery,
  type AuditScanRef,
} from "@/lib/db/scans";
export {
  purgeExpiredData,
  envRetentionDefaults,
  resolveRetention,
  clampBatchSize,
  PURGE_ACTION,
  RETENTION_DEFAULT_BATCH_SIZE,
  type RetentionPolicy,
  type OrgPurgeResult,
  type PurgeSummary,
} from "@/lib/db/retention";
export { getUsageSummary, type UsageSummary, type ProviderUsage, type UsageDay } from "@/lib/db/usage";
export {
  getCreditState,
  grantCredits,
  consumeScanCredit,
  getCreditLedger,
  isUnlimitedPlan,
  type CreditState,
  type CreditLedgerEntry,
} from "@/lib/db/credits";
export {
  ensureOwnerMembership,
  getMembershipRole,
  setMembershipRole,
  listOrgMembers,
  type OrgRole,
  type OrgMember,
} from "@/lib/db/members";
export {
  upsertInstallation,
  removeInstallation,
  unwatchReposForInstallation,
  reconcileWatchedRepos,
  getInstallationIdForOwner,
} from "@/lib/db/installations";
export { getSessionVersion, bumpSessionVersion } from "@/lib/db/sessions";
export {
  setRepoWatch,
  setRepoSchedule,
  setWatchedSchedule,
  seedWatchlist,
  listWatchedRepos,
  getOrgRollup,
  getRepoStates,
  getOrgContributors,
  getContributorInsights,
  getOrgPrSignals,
  getOrgGovernance,
  getOrgActivity,
  getOrgPractices,
  getOrgGapAnalysis,
  getOrgMovers,
  getOrgRecommendations,
  getOrgBacklog,
  dueBucketFor,
  getOrgDiscrepancies,
  getOrgBenchmark,
  getOrgTeamRollup,
  rollupTeams,
  listDueRescans,
  advanceSchedule,
  advanceScheduleAfterFailure,
  claimRescan,
  recordScanOutcome,
  listOrgsWithWatchedRepos,
  getOrgId,
  isRepoWatched,
  type DueRescan,
  type RepoRef,
  type OrgRepoRow,
  type OrgRollup,
  type OrgWindow,
  type RepoState,
  type OrgContributor,
  type ContributorInsight,
  type RepoConcentration,
  type ContributorInsights,
  type OrgPrSignals,
  type OrgGovernance,
  type RepoGovernance,
  type OrgActivity,
  type OrgPractice,
  type OrgGapAnalysis,
  type CommonGap,
  type RepoOutlier,
  type OrgMovers,
  type RepoMove,
  type OrgRec,
  type OrgBacklog,
  type BacklogItem,
  type BacklogOwnerGroup,
  type BacklogDueGroup,
  type BacklogDueBucket,
  type OrgBenchmark,
  type OrgDiscrepancies,
  type DiscrepancyGroup,
  type OrgTeamRollup,
  type TeamRollup,
  type TeamRepoScore,
  type TeamChampion,
  type TeamDimAvg,
  type TeamPairing,
  type TeamRollupRepoInput,
} from "@/lib/db/org";
export {
  listSegments,
  createSegment,
  updateSegment,
  deleteSegment,
  setRepoSegment,
  getSegmentOrgSlug,
  getRepoSegmentMap,
  compareSegments,
  listSegmentSummaries,
  buildSegmentComparison,
  normalizeSegmentName,
  normalizeColor,
  type SegmentRow,
  type SegmentSummary,
  type SegmentComparison,
} from "@/lib/db/segments";
export {
  createGoal,
  listGoals,
  updateGoal,
  deleteGoal,
  createInitiative,
  listInitiatives,
  updateInitiativeStatus,
  getGoalOrgSlug,
  getInitiativeOrgSlug,
  simulateOrgFix,
  isGoalMetric,
  metricLabel,
  type GoalProgress,
  type GoalMetric,
  type InitiativeRow,
} from "@/lib/db/plan";
export {
  listPlaybooks,
  createPlaybook,
  updatePlaybook,
  deletePlaybook,
  getPlaybookOrgSlug,
  applyPlaybook,
  unapplyPlaybook,
  getPlaybookAdoption,
  type PlaybookRow,
  type PlaybookInput,
  type PlaybookAdoption,
} from "@/lib/db/playbooks";
export {
  forecastTrajectory,
  forecastHeadline,
  humanizeDays,
  type Forecast,
  type LevelEta,
  type Trajectory,
  type SeriesPoint,
} from "@/lib/maturity/forecast";
