// Render a ScanReport into the "ultimate onboarding skill" — a single, self-contained SKILL.md the
// scanned repo drops into .claude/skills/ and runs with its own Claude Code CLI. Unlike the static
// practice-artifact PRs, this hands the repo an interactive HARNESS its own agent drives: it
// re-confirms each gap against the real code, adapts the deliverable to this repo, verifies before
// proposing, and tracks progress. That makes the skill itself a unit of LLM-driven development.
//
// Everything the running agent needs is BAKED IN, because the scanned repo has no access to
// Ascent's database. Pure string assembly (no LLM, no I/O) — deterministic and testable.

import type { ScanReport } from "@/lib/types";
import { ARCHETYPE_LABEL } from "@/lib/maturity/model";
import { buildFoundation, type GeneratedFile } from "@/lib/standard";
import { publicBaseUrl } from "@/lib/site";
import { selectTracks, WEAK_THRESHOLD, type OnboardingTrack, type SelectOpts } from "./tracks";

// Canonical product URL for the footer back-link. Prefer the configured public origin; fall back to
// the product's stable domain so the attribution in a downloaded SKILL.md never points at a placeholder.
const ASCENT_URL = "https://ascent.dev";

export interface GeneratedSkill {
  /** Skill identifier / slash-command name. */
  name: string;
  /** Repo-relative path the file should live at. */
  path: string;
  /** Full SKILL.md body to write. */
  body: string;
  /** The practice/track ids this skill selected — persisted for the generation history (STD-6). */
  trackIds: string[];
}

const SKILL_NAME = "ascent-onboard";

/** Build the onboarding skill for a report. `opts` forwards to track selection (e.g. an explicit
 *  maintainer multiselect); by default the weak dimensions are chosen automatically. */
export function buildOnboardingSkill(report: ScanReport, opts?: SelectOpts): GeneratedSkill {
  const tracks = selectTracks(report, opts);
  const body = [
    frontmatter(report, tracks),
    mission(report),
    currentState(report, tracks),
    controlModel(),
    foundation(report),
    tracksMenu(tracks),
    runProtocol(tracks),
    guardrails(),
    footer(report),
  ].join("\n\n"); // blank line between every section so headings/`---` aren't glued to prose
  return { name: SKILL_NAME, path: `.claude/skills/${SKILL_NAME}/SKILL.md`, body, trackIds: tracks.map((t) => t.id) };
}

// ---- sections -----------------------------------------------------------------

function frontmatter(report: ScanReport, tracks: OnboardingTrack[]): string {
  const repo = `${report.repo.owner}/${report.repo.name}`;
  const dims = tracks.map((t) => t.dimId).join(", ") || "no open gaps";
  const desc =
    `Personalized AI-native onboarding for ${repo} — generated by Ascent from a scan on ` +
    `${report.scannedAt.slice(0, 10)} (currently ${report.level.id} ${report.level.name}, ` +
    `${report.overallScore}/100). Run it to adopt the highest-leverage practices (${dims}) that ` +
    `move this repo toward autonomous, LLM-driven development.`;
  // The description is a single YAML line: collapse any newline (and the quotes) so an interpolated
  // value can't break out of the quoted scalar and corrupt the frontmatter block.
  const safeDesc = desc.replace(/[\r\n]+/g, " ").replace(/"/g, "'");
  return `---
name: ${SKILL_NAME}
description: "${safeDesc}"
---`;
}

function mission(report: ScanReport): string {
  return `# Ascent onboarding — ${report.repo.owner}/${report.repo.name}

You are the **Ascent onboarding agent** for *this* repository. Your job is to raise its AI-native
maturity on the tracks the maintainer selects — not by pasting boilerplate, but by adapting each
practice to this codebase, verifying as you go, and leaving the repo measurably more autonomous.

**North star: LLM-driven development.** A repo where agents can safely propose, test, document, and
ship, with humans supervising at the policy level. Every track below is framed by what it *unlocks
for agents*, not as generic hygiene.

This file was generated from an Ascent scan and has the findings **baked in** — you do not need to
re-derive the score. You DO need to re-confirm each specific gap against the live code before acting
(a scan can go stale).`;
}

function scoreLine(label: string, value: number): string {
  const filled = Math.round(value / 10);
  const bar = "█".repeat(filled) + "░".repeat(10 - filled);
  return `- **${label}:** ${value}/100  \`${bar}\``;
}

function currentState(report: ScanReport, tracks: OnboardingTrack[]): string {
  const selected = new Set(tracks.map((t) => t.dimId));
  const rows = report.dimensions
    .map((d) => {
      const status = d.score >= WEAK_THRESHOLD ? "✓ strength" : selected.has(d.id) ? "→ track below" : "gap";
      return `| ${d.id} | ${d.name} | ${d.score} | ${status} |`;
    })
    .join("\n");
  const strengths = report.strengths.slice(0, 4).map((s) => `- ${s}`).join("\n");
  return `## Where this repo stands (from the scan)

- **Level:** ${report.level.id} — ${report.level.name} (${report.level.tagline})
- **Posture:** ${report.posture.label} — ${report.posture.blurb}
- **Run style:** ${ARCHETYPE_LABEL[report.archetype]} lens
${scoreLine("Overall", report.overallScore)}
${scoreLine("Adoption (are you using AI?)", report.adoptionScore)}
${scoreLine("Rigor (can you ship it safely?)", report.rigorScore)}

| Dim | Name | Score | Status |
|-----|------|-------|--------|
${rows}

**Already strong here — keep it:**
${strengths || "- (the scan surfaced no standout strengths yet)"}`;
}

function controlModel(): string {
  return `## The control model — push controls LEFT of CI

A CI gate fires **after** a branch is pushed. By then a leaked secret has already left the machine
and a failed gate is a wasted round-trip. In an LLM-driven workflow the **agent is the first line of
control**, so this skill places work in two layers — and most of it is *not* in CI:

1. **Repo / pre-push (primary).** A checklist the agent self-runs *before* pushing — encoded in
   agent guidance (CLAUDE.md/AGENTS.md), local git hooks, and your verify-before-propose loop. Fast,
   local, and it catches problems before they ever leave the box.
2. **CI / hard pass (thin backstop).** Only the non-negotiables that truly need a remote, clean-room,
   or full-tree environment: SAST over the whole tree, the merge gate itself, scheduled scans. CI
   *confirms* what the agent already enforced; it is not the enforcer.

When you adopt a track, **extend the mechanisms this repo already has** (e.g. an existing lefthook /
husky config, an existing CI workflow) rather than adding a parallel one. Each track below tells you
which layer its controls belong in.`;
}

function embedFile(f: GeneratedFile): string {
  // Fence with MORE backticks than the longest backtick run anywhere in the body, so nothing inside —
  // even a four-backtick line — can close the fence early and leak/garble everything below it. The old
  // fixed four-backtick fence merely ASSUMED bodies never contained four backticks (the hand-authored
  // .mjs scripts dodge it on purpose, but nothing enforced it for a generated body).
  const longestRun = (f.body.match(/`+/g) ?? []).reduce((m, run) => Math.max(m, run.length), 0);
  const fence = "`".repeat(Math.max(4, longestRun + 1));
  return `#### \`${f.path}\`
_${f.purpose}_

${fence}${f.lang}
${f.body}${fence}`;
}

function foundation(report: ScanReport): string {
  const files = buildFoundation(report);
  const blocks = files.map(embedFile).join("\n\n");
  const paths = files.map((f) => `\`${f.path}\``).join(", ");
  return `## Step 0 — Lay the foundation (the \`.ai/\` standard)

Before any dimension track, install the **foundation**: a small, vendor-neutral standard that makes
this repo *legible, verifiable, and self-maintaining* for agents. It is the spine everything else
hangs on, so do it first.

- **Legible** — \`.ai/manifest.yaml\` is one contract an agent reads to bootstrap: capabilities (a
  name → the command that fulfils it, never a tool), pointers to where memory/context/evals live, the
  boundaries, and the control placement. Capability-not-tool + pointers-not-embeds let it survive tool churn.
- **Verifiable** — \`.ai/doctor.mjs\` *proves* those claims in-repo, pre-push (the control model applied
  to the standard itself). Run \`node .ai/doctor.mjs\` for a conformance baseline now, and after each track.
- **Self-maintaining** — \`.ai/memory/\` is durable, agent-written memory (decisions, gotchas,
  dead-ends); the \`CONTEXT.md\` graph keeps per-module docs fresh.

**Write these files** (${paths}), adapting every \`TODO\` to this repo (real \`purpose\`, \`secretsFrom\`,
\`neverTouch\`, \`agents\`, and per-module \`CONTEXT.md\` files). Then run the doctor and fix any **FAIL** —
a pre-push control with no local hook is the highest-severity one. Record the adoption in \`.ai/memory/\`.

**Wire the doctor into both layers — one script.** Add \`node .ai/doctor.mjs\` to this repo's *existing*
pre-push hook (extend lefthook / husky / pre-commit — never add a parallel hook system); that's the
primary, pre-push control. The generated \`.github/workflows/ai-conformance.yml\` runs the *same*
command on the merge gate as the thin backstop. The agent self-certifies locally; CI only confirms.

**Keep it fresh — onboarding becomes upkeep.** Also add \`node .ai/maintain.mjs check\` to the pre-push
hook: it warns when a changed module's \`CONTEXT.md\` wasn't refreshed, so the docs can't silently rot.
After a task, log what you learned with \`node .ai/maintain.mjs note <kind> "<one fact>"\` (it appends a
correctly-numbered, dated memory entry), and once you refresh a module's \`CONTEXT.md\` run
\`node .ai/maintain.mjs touch <module-path>\` to reconcile its freshness anchor. The repo maintains its
own legibility instead of decaying between scans.

${blocks}`;
}

function tracksMenu(tracks: OnboardingTrack[]): string {
  if (tracks.length === 0) {
    return `## Tracks

The scan found no open dimension below ${WEAK_THRESHOLD}/100 — this repo is already broadly
AI-native. Re-scan after any major change, or pass specific dimensions to revisit a refinement.`;
  }
  const blocks = tracks.map((t, i) => trackBlock(t, i + 1)).join("\n\n");
  return `## Tracks (highest leverage first)

${blocks}`;
}

function bullets(items: string[]): string {
  return items.map((s) => `  - ${s}`).join("\n");
}

function trackBlock(t: OnboardingTrack, n: number): string {
  const unlock = t.levelUnlock ? ` · unlocks ${t.levelUnlock}` : "";
  const gaps = t.gaps.length ? t.gaps.map((g) => `  - ${g}`).join("\n") : "  - (re-confirm against the live code)";
  const explore = t.explore.length
    ? `\n- **Questions to explore (inputs, not directives):**\n${t.explore.map((q) => `  - ${q}`).join("\n")}`
    : "";
  return `### ${n}. ${t.title} — ${t.dimId} ${t.dimName} (now ${t.score}/100)

> **Unlocks:** ${t.autonomyUnlock}

- **Why (from the scan):** ${t.why}
- **Impact / effort:** ${t.impact} / ${t.effort}${unlock}
- **Scan-found gaps:**
${gaps}
- **Deliverable anchor:** \`${t.deliverable.path}\` — ${t.deliverable.summary}
- **Primary layer:** ${layerLabel(t.primaryLayer)}
- **Pre-push checklist (the primary control — local, before the branch leaves the box):**
${bullets(t.prePushChecklist)}
- **CI hard passes (thin backstop only):**
${bullets(t.ciHardPasses)}
- **Definition of done:**
${bullets(t.definitionOfDone)}${explore}`;
}

function layerLabel(layer: OnboardingTrack["primaryLayer"]): string {
  switch (layer) {
    case "pre-push":
      return "pre-push (repo level) — keep it out of CI";
    case "ci-hard-pass":
      return "CI hard pass — needs a clean-room / full-tree run";
    case "both":
      return "both — lead with the pre-push checklist, keep a thin CI backstop";
  }
}

function runProtocol(tracks: OnboardingTrack[]): string {
  const order = tracks.map((t, i) => `${i + 1}. ${t.title} (${t.dimId})`).join("\n");
  return `## How to run this skill

0. **Lay the foundation first** (Step 0 above): write the \`.ai/\` files, adapt the TODOs, and run
   \`node .ai/doctor.mjs\` for a conformance baseline. The tracks build on it.

1. **Let the maintainer choose.** Present the tracks above as a **multiselect** (use your
   question/checklist UI) and let them pick which to take this session. Default order by leverage:
${order ? order.split("\n").map((l) => `   ${l}`).join("\n") : "   (none — repo is already strong)"}

2. **For each selected track, in order:**
   1. **Re-confirm the gap** against the live code — the scan may be stale. If the repo already
      covers it another way, say so and skip rather than duplicate.
   2. **Adapt, don't paste.** Build the deliverable for *this* repo: real commands from its
      manifest, the real module map, the real critical paths. **Extend existing hooks/workflows**
      (lefthook/husky, current CI) instead of adding a parallel mechanism.
   3. **Place controls correctly** per the control model: put the pre-push checklist in agent
      guidance + local hooks first; add a CI step only for the listed hard passes.
   4. **Show the diff and get confirmation.** One focused PR per track.
   5. **Verify** with the repo's own commands (tests, lint, typecheck, and the new local checks)
      before proposing the change. Never propose a diff you haven't verified.
   6. **Record progress as a memory:** \`node .ai/maintain.mjs note progress "<track>: what changed, what's left"\`
      appends a dated entry under \`.ai/memory/\` (the store from Step 0 — don't invent a second ledger).
      Re-running this skill resumes from the memory log.
   7. **Capture the non-obvious as you go** — the highest-signal memories, and the ones this standard
      exists to build. When you hit a wrong turn, log it so the next run (or a teammate) doesn't repeat
      it: \`node .ai/maintain.mjs note failed-approach "<what you tried + why it didn't work>"\`. When you
      make a non-obvious call, record the reasoning: \`node .ai/maintain.mjs note decision "<the choice + why>"\`.

3. **Close the loop.** Summarize what changed, which checks now run pre-push vs. CI, and the level
   transition each track targets. Tell the maintainer to **re-scan in Ascent** to confirm the new
   score — the scan, not this skill, is the source of truth.`;
}

function guardrails(): string {
  return `## Guardrails (non-negotiable)

- **Never fabricate architecture, commands, or constraints you can't verify in the repo.** Leave a
  clearly-marked TODO instead of inventing.
- **Small, reversible changes.** One track = one PR. Don't bundle.
- **Keep a human in the loop.** This skill *suggests and prepares*; it never auto-merges. Preserve a
  human-confirmation checkpoint on every change.
- **Attribute AI work** (e.g. a \`Co-Authored-By\` trailer) so the history stays honest.
- **Don't regress.** If adopting a track would break an existing check, fix the track, not the check.`;
}

function footer(report: ScanReport): string {
  const site = publicBaseUrl() || ASCENT_URL;
  return `---

_Generated by [Ascent](${site}) — your AI-native maturity companion — from a scan of
\`${report.repo.owner}/${report.repo.name}\` on ${report.scannedAt.slice(0, 10)} ` +
    `(${report.level.id} ${report.level.name}, ${report.overallScore}/100, engine: ${report.engine.provider}).
Re-scan after adopting tracks to confirm the new score._`;
}
