// Step 0 of the generated onboarding SKILL.md - the `.ai/` foundation, rendered in ONE of TWO lanes.
//
// WHY TWO LANES. `buildFoundation` commits the real `.ai/` tree AND a SKILL.md beside it. Embedding
// every one of those bodies verbatim inside that SKILL.md gave the adopting repo the doctor twice:
// once as the file its pre-push hook runs, once as ~30KB of fenced text inside an always-loaded
// instruction file. That is a second authority for the same fact, in the same pull request, and it is
// exactly what the standard this code generates forbids under its own principle 2 (pointers, not
// embeds). It also pushed the instruction file past the size at which an agent still reads it.
//
//  - `reference` (the PR lane, and the local install lane): the files are already on disk beside the
//    skill, so Step 0 is a DERIVED pointer list - each path, its purpose, and a sha256 stamp taken
//    from the passed `files`, so the list can never go stale against the generator.
//  - `embed` (the plain markdown download, and the default): there is no repo to point at, so every
//    body stays verbatim. It gains the provenance stamp instead, in the same shape the guidance
//    projections use, so a transcribed copy stays comparable to the source it came from.
//
// The stamp sits OUTSIDE the fence on purpose. Inside it, it would change the body an adopter
// transcribes, which is the one thing the embed lane exists to deliver byte-exact.

import type { GeneratedFile } from "@/lib/standard/types";
import { renderProjectionHeader, sha12 } from "@/lib/analyze/guidance-projection";
import { publicBaseUrl } from "@/lib/site";

export type Step0Mode = "embed" | "reference";

/** The section heading both lanes carry, so a caller can locate Step 0 in the rendered body. */
export const STEP0_HEADING = "## Step 0 — Lay the foundation (the `.ai/` standard)";

/**
 * The provenance stamp for one embedded body. Source hash and body hash are the SAME hash, because an
 * embed is a verbatim copy: the pair shape is reused rather than reinvented so the repo has exactly
 * one provenance convention and one parser for it (`.ai/doctor.mjs` already reads this header).
 */
function stamp(f: GeneratedFile): string {
  const h = sha12(f.body);
  return renderProjectionHeader({ sourcePath: f.path, sourceHash: h, bodyHash: h });
}

function embedFile(f: GeneratedFile): string {
  // Fence with MORE backticks than the longest backtick run anywhere in the body, so nothing inside -
  // even a four-backtick line - can close the fence early and leak/garble everything below it. The old
  // fixed four-backtick fence merely ASSUMED bodies never contained four backticks (the hand-authored
  // .mjs scripts dodge it on purpose, but nothing enforced it for a generated body).
  const longestRun = (f.body.match(/`+/g) ?? []).reduce((m, run) => Math.max(m, run.length), 0);
  const fence = "`".repeat(Math.max(4, longestRun + 1));
  return `#### \`${f.path}\`
_${f.purpose}_

${fence}${f.lang}
${f.body}${fence}

${stamp(f)}`;
}

/** One table cell: a purpose is free prose, so a pipe or a newline in it must not break the row. */
function cell(text: string | undefined): string {
  return (text ?? "").replace(/\r?\n/g, " ").replace(/\|/g, "\\|");
}

/** The derived pointer list: exactly the files passed, in order, each with its purpose and body hash. */
function referenceTable(files: readonly GeneratedFile[]): string {
  const rows = files.map((f) => `| \`${f.path}\` | \`${sha12(f.body)}\` | ${cell(f.purpose)} |`).join("\n");
  return `| File | sha256 | What it is |
| --- | --- | --- |
${rows}`;
}

/**
 * The recovery path for a file this install did not land. The PR installer SKIPS a path the repo
 * already has (a pre-existing root `CONTEXT.md`, its own workflow), so a pointer list can name a file
 * that is not there, and the reader needs a way to get its body.
 *
 * The host is the deployment's OWN origin or nothing, the same rule the footer follows: this file is
 * generated by a self-hostable AGPL build, and sending an adopter to a product domain where they have
 * no account and no scan damages the instruction more than omitting it does.
 */
function recovery(repo: { owner: string; name: string }): string {
  const site = publicBaseUrl();
  const where = site
    ? `download the full inline copy from ${site}/api/report/skill?repo=${repo.owner}/${repo.name}`
    : `re-export the onboarding skill from the Ascent deployment that scanned this repo`;
  return `**If a file in that table is not in this pull request**, the installer skipped it because the repo
already has something at that path. Do not overwrite it: reconcile by hand, and if you need the
generated body to compare against, ${where} (that export still carries every body inline).`;
}

/** The half of Step 0 that is the same in both lanes: what the foundation is, and how to wire it. */
function preamble(): string {
  return `${STEP0_HEADING}

Before any dimension track, install the **foundation**: a small, vendor-neutral standard that makes
this repo *legible, verifiable, and self-maintaining* for agents. It is the spine everything else
hangs on, so do it first.

- **Legible** — \`.ai/manifest.yaml\` is one contract an agent reads to bootstrap: capabilities (a
  name → the command that fulfils it, never a tool), pointers to where memory/context/evals live, the
  boundaries, and the control placement. Capability-not-tool + pointers-not-embeds let it survive tool churn.
- **Verifiable** — \`.ai/doctor.mjs\` *proves* those claims in-repo, pre-push (the control model applied
  to the standard itself). Run \`node .ai/doctor.mjs\` for a conformance baseline now, and after each track.
- **Self-maintaining** — \`.ai/memory/\` is durable, agent-written memory (decisions, gotchas,
  dead-ends); the \`CONTEXT.md\` graph keeps per-module docs fresh.`;
}

/** The half that is the same in both lanes: wire the doctor, then keep it fresh. */
function wiring(): string {
  return `**Wire the doctor into both layers — one script.** Add \`node .ai/doctor.mjs\` to this repo's *existing*
pre-push hook (extend lefthook / husky / pre-commit — never add a parallel hook system); that's the
primary, pre-push control. The generated \`.github/workflows/ai-conformance.yml\` runs the *same*
command on the merge gate as the thin backstop. The agent self-certifies locally; CI only confirms.

**Keep it fresh — onboarding becomes upkeep.** Also add \`node .ai/maintain.mjs check\` to the pre-push
hook: it warns when a changed module's \`CONTEXT.md\` wasn't refreshed, so the docs can't silently rot.
After a task, log what you learned with \`node .ai/maintain.mjs note <kind> "<one fact>"\` (it appends a
correctly-numbered, dated memory entry), and once you refresh a module's \`CONTEXT.md\` run
\`node .ai/maintain.mjs touch <module-path>\` to reconcile its freshness anchor. The repo maintains its
own legibility instead of decaying between scans.`;
}

/**
 * Render Step 0 for `files` in `mode`. `repo` only supplies the recovery link's `?repo=` segment; it
 * is unused in embed mode, where nothing can be missing from a tree the file itself carries.
 */
export function renderStep0(
  files: readonly GeneratedFile[],
  mode: Step0Mode,
  repo: { owner: string; name: string },
): string {
  if (mode === "reference") {
    return `${preamble()}

**These files are already in this pull request** — read them there rather than re-deriving them, and
do not paste a second copy anywhere. The table is the manifest of what landed, with the sha256 of each
generated body so you can tell an untouched file from one somebody has since edited.

${referenceTable(files)}

${recovery(repo)}

**Adapt every \`TODO\` to this repo** (real \`purpose\`, \`secretsFrom\`, \`neverTouch\`, \`agents\`, and
per-module \`CONTEXT.md\` files). Then run the doctor and fix any **FAIL** — a pre-push control with no
local hook is the highest-severity one. Record the adoption in \`.ai/memory/\`.

${wiring()}`;
  }

  const blocks = files.map(embedFile).join("\n\n");
  const paths = files.map((f) => `\`${f.path}\``).join(", ");
  return `${preamble()}

**Write these files** (${paths}), adapting every \`TODO\` to this repo (real \`purpose\`, \`secretsFrom\`,
\`neverTouch\`, \`agents\`, and per-module \`CONTEXT.md\` files). Then run the doctor and fix any **FAIL** —
a pre-push control with no local hook is the highest-severity one. Record the adoption in \`.ai/memory/\`.

${wiring()}

${blocks}`;
}
