// Write a set of GENERATED files into a local working copy — the delivery half of an "install" for
// the doors that have no GitHub App in the room (the loop's foundation and practice lanes).
//
// The two cloud doors and the two local lanes now share their GENERATORS (`buildFoundation` in
// @/lib/standard, `buildPracticeArtifact` in @/lib/practices/artifact); what they cannot share is
// delivery, because one commits through the GitHub contents API and the other writes to disk. This
// module is that second delivery, and it deliberately copies `openDraftPr`'s COLLISION POLICY rather
// than relaxing it:
//
//   • the SPINE (files[0], under `spineGuard`) already present means the thing is already installed —
//     nothing is written at all, and the caller says so. Mirrors the 409 that propagates out of
//     openFoundationPr for `.ai/manifest.yaml`.
//   • any LATER file already present is a real file the repo owns (a repo may well have its own
//     `CONTEXT.md` or `AGENTS.md`). It is skipped and reported, never overwritten.
//
// A worktree install that quietly rewrote a repo's real AGENTS.md would be a strictly worse outcome
// than the PR path's refusal — the agent lane exists for changing files that already exist.

import { mkdir, stat, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, relative, resolve } from "node:path";

/** The minimum a generated file needs to be installable. `GeneratedFile` and `ArtifactSpec` both fit. */
export interface InstallableFile {
  path: string;
  body: string;
}

export interface InstallResult {
  /** Repo-relative paths actually written, in scaffold order. */
  written: string[];
  /** Paths left alone because the repo already has a real file there (or the path was unsafe). */
  skipped: string[];
  /** True when the spine was already present — nothing was written. Only ever set under `spineGuard`. */
  alreadyInstalled: boolean;
}

/**
 * Resolve a repo-relative path inside `dir`, or null when it escapes.
 *
 * The paths here are generated by Ascent's own builders rather than typed by a user, so this is
 * defense in depth — but the value being written is a whole file into a directory the operator
 * works in, which is exactly the blast radius that makes a containment check cheap insurance.
 */
export function resolveInside(dir: string, rel: string): string | null {
  if (!rel || isAbsolute(rel)) return null;
  const root = resolve(dir);
  const abs = resolve(root, rel);
  const rp = relative(root, abs);
  return rp === "" || rp.startsWith("..") || isAbsolute(rp) ? null : abs;
}

async function exists(abs: string): Promise<boolean> {
  return stat(abs).then(
    () => true,
    () => false,
  );
}

/**
 * Write every file that is not already there, creating parent directories as needed.
 *
 * @param spineGuard treat `files[0]` as the spine: if it exists, write NOTHING and report
 *                   `alreadyInstalled`. Used by the foundation lane; a single-file practice
 *                   artifact has no spine semantics and passes it as false.
 */
export async function installFiles(
  dir: string,
  files: readonly InstallableFile[],
  opts: { spineGuard?: boolean } = {},
): Promise<InstallResult> {
  const written: string[] = [];
  const skipped: string[] = [];
  for (const [i, f] of files.entries()) {
    const abs = resolveInside(dir, f.path);
    if (!abs) {
      skipped.push(f.path);
      continue;
    }
    if (await exists(abs)) {
      if (i === 0 && opts.spineGuard === true) return { written: [], skipped: [], alreadyInstalled: true };
      skipped.push(f.path);
      continue;
    }
    await mkdir(dirname(abs), { recursive: true });
    await writeFile(abs, f.body, "utf8");
    written.push(f.path);
  }
  return { written, skipped, alreadyInstalled: false };
}
