// The DETERMINISTIC lane body, driven against a real git repository.
//
// Real fs + real git, because both are the deliverable: "wrote the files" and "landed a commit" are
// the two claims a foundation/practice lane makes, and a mocked git would let either regress
// silently. Only the two DB reads (the persisted scan, the org's mined practice shapes) are faked.
//
// The last case is the one that matters most: it drives BOTH doors — `openFoundationPr` (the cloud
// draft PR) and the lane's install — off the same report and asserts the bytes are identical. That is
// the property the refactor exists to protect; without it, "the same generator" is a comment.

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import { levelForScore } from "@/lib/maturity/model";
import type { ScanReport } from "@/lib/types";

function makeReport(): ScanReport {
  return {
    repo: {
      owner: "acme", name: "api", url: "https://github.com/acme/api", description: "Billing API",
      stars: 12, forks: 1, primaryLanguage: "TypeScript", defaultBranch: "main", headSha: "abc1234",
    },
    overallScore: 58, level: levelForScore(58), archetype: "team",
    adoptionScore: 55, rigorScore: 60,
    posture: { id: "ai-native", label: "AI-Native", blurb: "x" },
    aiUsage: { detected: true, commitFraction: 0.3, signals: [] },
    contributors: [], dimensions: [],
    headline: "h", strengths: [], risks: [], roadmap: [], discrepancies: [],
    confidence: 0.8, scannedAt: "2026-06-10T00:00:00.000Z",
    engine: { provider: "mock", model: "deterministic" },
  };
}

const scan = { report: makeReport() as ScanReport | null };
vi.mock("@/lib/db", () => ({ getScanReportByCommit: vi.fn(async () => scan.report) }));
vi.mock("@/lib/db/org-practice-shapes", () => ({ getOrgPracticeShapes: vi.fn(async () => null) }));

// The cloud door's ONLY side effect, captured so the parity case can compare what it would commit.
const seeded: { path: string; content: string }[] = [];
vi.mock("@/lib/github/app", () => ({
  AppApiError: class AppApiError extends Error {
    status = 0;
  },
}));
vi.mock("@/lib/github/write", () => ({
  openDraftPr: vi.fn(async (a: { path: string; content: string }) => {
    seeded.push({ path: a.path, content: a.content });
    return { number: 1, url: "https://example.test/pr/1", reused: false };
  }),
}));

import { installInWorktree } from "./lane-install";
import { buildFoundation } from "@/lib/standard";
import { openFoundationPr } from "@/lib/standard/pr";

const dirs: string[] = [];

function gitRepo(files: Record<string, string> = {}): string {
  const dir = mkdtempSync(join(tmpdir(), "ascent-lane-install-"));
  dirs.push(dir);
  const git = (...args: string[]) => execFileSync("git", args, { cwd: dir, stdio: "pipe" });
  git("init", "-q");
  git("config", "user.email", "loop@ascent.test");
  git("config", "user.name", "Ascent Loop");
  git("config", "commit.gpgsign", "false");
  writeFileSync(join(dir, "README.md"), "seed\n", "utf8");
  for (const [rel, body] of Object.entries(files)) {
    const abs = join(dir, rel);
    mkdirSync(join(abs, ".."), { recursive: true });
    writeFileSync(abs, body, "utf8");
  }
  git("add", "-A");
  git("commit", "-q", "-m", "seed");
  return dir;
}

const log = (dir: string): string => execFileSync("git", ["log", "--format=%B%n--"], { cwd: dir, encoding: "utf8" });
const head = (dir: string): string => execFileSync("git", ["rev-parse", "HEAD"], { cwd: dir, encoding: "utf8" }).trim();

beforeEach(() => {
  scan.report = makeReport();
  seeded.length = 0;
});
afterEach(() => {
  for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
});

describe("installInWorktree — foundation", () => {
  it("writes the whole generated tree and lands ONE commit", async () => {
    const dir = gitRepo();
    const before = head(dir);
    const res = await installInWorktree({ dir, org: "acme", repo: "acme/api", kind: "foundation" });

    expect(res.ok).toBe(true);
    expect(res.committed).toBe(true);
    expect(res.written).toContain(".ai/manifest.yaml");
    expect(res.written.length).toBe(buildFoundation(makeReport()).length);
    expect(readFileSync(join(dir, ".ai/manifest.yaml"), "utf8")).toContain("capabilities");
    // One commit, and the worktree is clean afterwards — nothing left unstaged for the next cycle.
    expect(head(dir)).not.toBe(before);
    expect(execFileSync("git", ["status", "--porcelain"], { cwd: dir, encoding: "utf8" }).trim()).toBe("");
    expect(log(dir)).toContain("chore(.ai): install the AI-native foundation");
  });

  it("refuses to overwrite a repo's own file, and says which it skipped", async () => {
    // CONTEXT.md is generated by the scaffold; a repo that already has one keeps it.
    const dir = gitRepo({ "CONTEXT.md": "# mine, not Ascent's\n" });
    const res = await installInWorktree({ dir, org: "acme", repo: "acme/api", kind: "foundation" });
    expect(res.ok).toBe(true);
    expect(res.skipped).toContain("CONTEXT.md");
    expect(res.written).not.toContain("CONTEXT.md");
    expect(readFileSync(join(dir, "CONTEXT.md"), "utf8")).toBe("# mine, not Ascent's\n");
    expect(log(dir)).toContain("Skipped (the repository already has them)");
  });

  it("writes NOTHING when the spine is already there — the same 409 the PR door raises", async () => {
    const dir = gitRepo({ ".ai/manifest.yaml": "version: 1\n" });
    const before = head(dir);
    const res = await installInWorktree({ dir, org: "acme", repo: "acme/api", kind: "foundation" });
    expect(res.ok).toBe(true);
    expect(res.committed).toBe(false);
    expect(res.written).toEqual([]);
    expect(res.summary).toMatch(/already installed/i);
    expect(head(dir)).toBe(before);
  });

  it("declines when the repo has no saved scan to generate from", async () => {
    scan.report = null;
    const res = await installInWorktree({ dir: gitRepo(), org: "acme", repo: "acme/api", kind: "foundation" });
    expect(res.ok).toBe(false);
    expect(res.committed).toBe(false);
    expect(res.summary).toMatch(/no saved scan/i);
  });
});

describe("installInWorktree — practice", () => {
  it("writes the starter and carries the follow-up's trailer, so the rescan can adjudicate it", async () => {
    const dir = gitRepo();
    const res = await installInWorktree({
      dir,
      org: "acme",
      repo: "acme/api",
      kind: "practice",
      practiceId: "agent-guidance",
      resolvesId: "rec-42",
    });
    expect(res.ok).toBe(true);
    expect(res.committed).toBe(true);
    expect(res.written).toEqual(["AGENTS.md"]);
    expect(readFileSync(join(dir, "AGENTS.md"), "utf8")).toContain("agent guidance");
    expect(log(dir)).toContain("Ascent-Resolves: rec-42");
  });

  it("declines an unknown practice id rather than committing something empty", async () => {
    const res = await installInWorktree({ dir: gitRepo(), org: "acme", repo: "acme/api", kind: "practice", practiceId: "nope" });
    expect(res.ok).toBe(false);
    expect(res.summary).toMatch(/unknown practice/i);
  });
});

describe("the two doors generate the same bytes", () => {
  it("the lane's files are byte-identical to what openFoundationPr seeds", async () => {
    const dir = gitRepo();
    await installInWorktree({ dir, org: "acme", repo: "acme/api", kind: "foundation" });

    await openFoundationPr({
      token: "t",
      owner: "acme",
      repo: "api",
      files: buildFoundation(makeReport()),
      prTitle: "Install the .ai/ AI-native foundation",
      prBody: "body",
    });

    expect(seeded.length).toBeGreaterThan(0);
    for (const f of seeded) {
      expect(readFileSync(join(dir, f.path), "utf8"), `${f.path} differs between the PR door and the lane`).toBe(f.content);
    }
  });
});
