// MOONSHOT #33 — a registry PRACTICE.md, turned into a committable starter. PURE (no db, no I/O).
//
// The registry-origin practices were deliberately READ-ONLY: `RegistryPractices.tsx` renders them with
// an "open in registry" link and no Apply button, on the reasoning that "they are files under someone
// else's review process, so the only affordance that can be honest is the file itself".
//
// That reasoning holds for EDITING and is why nothing here writes back to the registry. It does not
// hold for DISTRIBUTION: copying the org's own agreed practice into a repo that lacks it, as a draft PR
// that repo's own reviewers must approve, is exactly the reuse the registry exists for — and it lands
// through the same `applyPracticeToRepo` writer, the same draft-PR-never-a-push rule, and the same
// audit row as every other apply. One write path, no fork.
//
// PROVENANCE IS NOT DECORATION. The committed file names the registry path it came from and its
// content digest, because a reader who cannot tell an org standard from a generic template will treat
// both as boilerplate — the same distinction `buildArtifact` draws between a house pattern and a
// generic starter.

import type { ArtifactSpec } from "@/lib/practice-artifact";
import { safeText } from "@/lib/practice-artifact";

/** The `registry:` id prefix. The one place the convention is spelled. */
export const REGISTRY_PRACTICE_PREFIX = "registry:";

/** `registry:pr-review` → `pr-review`; null for anything else. */
export function registrySlugOf(practiceId: string): string | null {
  if (!practiceId.startsWith(REGISTRY_PRACTICE_PREFIX)) return null;
  const slug = practiceId.slice(REGISTRY_PRACTICE_PREFIX.length).trim();
  return slug.length > 0 ? slug : null;
}

/** The subset of an `OrgPracticeShape` row this builder reads. */
export interface RegistryPracticeSource {
  slug: string;
  title: string;
  appliesWhen: string;
  dimension: string;
  /** The PRACTICE.md body, frontmatter stripped. */
  content: string;
  /** Where it lives in the registry repo, e.g. `practices/pr-review/PRACTICE.md`. */
  registryPath: string | null;
  archived: boolean;
}

/** The path a registry starter lands at — DETERMINISTIC, because the adoption ledger keys on it. */
export const registryArtifactPath = (slug: string) => `docs/practices/${slug}.md`;

/**
 * Build the committable artifact for one registry practice, or null when there is nothing honest to
 * commit: an ARCHIVED row (the registry path vanished — re-distributing it would spread a document the
 * org has withdrawn) or EMPTY content (a file with no body is not a practice, and ascent never commits
 * an empty file into a customer's repository).
 */
export function buildRegistryArtifact(row: RegistryPracticeSource): ArtifactSpec | null {
  if (row.archived) return null;
  const content = row.content.trim();
  if (content.length === 0) return null;

  const slug = row.slug;
  const title = safeText(row.title || slug);
  const where = row.registryPath ? safeText(row.registryPath) : null;
  const applies = row.appliesWhen ? safeText(row.appliesWhen) : null;

  const provenance = where
    ? `> **From your organization's registry** — \`${where}\`. This file is a COPY: the source of truth stays in the registry and changes there by pull request, not here.`
    : `> **From your organization's registry.** This file is a COPY: the source of truth stays in the registry and changes there by pull request, not here.`;

  const body = `# ${title}

${provenance}
${applies ? `>\n> _Applies when: ${applies}_\n` : ""}
${content}
`;

  return {
    practiceId: `${REGISTRY_PRACTICE_PREFIX}${slug}`,
    path: registryArtifactPath(slug),
    body,
    commitMessage: `docs: adopt the "${title}" practice from our registry (via Ascent)`,
    branch: `ascent/registry-${slug}`,
    prTitle: `Adopt registry practice: ${title}`,
    prBody: `This draft copies your organization's own agreed practice **${title}**${
      where ? ` (\`${where}\`)` : ""
    } into this repository.

${applies ? `_Applies when: ${applies}_\n\n` : ""}It is a COPY for reference in this repo. The registry keeps the source of truth — edit it there, not in this file, or the two will diverge silently.

Generated by Ascent from your registry index${row.dimension ? ` · ${safeText(row.dimension)}` : ""}.`,
  };
}
