-- WHICH COMMAND A LANE'S VERIFICATION VERDICT IS ABOUT.
--
-- The A/B degradation guard assumed a git worktree could run the repository's own check. Measured on
-- both campaign repositories at the same commit, with `node_modules` linked exactly as the lane links
-- it, that assumption does not hold: `xkazm04/systedo-case` passes 3744/3744 in the paired checkout
-- and fails 8 in the worktree (every failure a missing Google application-default credential),
-- `xkazm04/kp` fails 2 routes needing local state. A worktree carries tracked files plus linked
-- dependency caches and none of the gitignored credentials, service config or local databases a
-- realistic suite reaches for -- so the guard established no baseline on either repo, protected
-- nothing, and blocked every delivery.
--
-- The guard now NARROWS: when the declared command cannot establish a baseline it walks down to the
-- strongest hermetic check that can (a typecheck, then a lint) and verifies against that.
--
-- This column records which rung the verdict is about: 'primary' | 'typecheck' | 'lint'. It exists
-- because "verified" and "verified against the typechecker only" are different facts, and a reader
-- must never be able to mistake one for the other.
--
-- NULL is the correct value for every pre-existing row and there is deliberately NO backfill: those
-- lanes were measured before the ladder existed, and writing 'primary' into them would be inventing a
-- provenance nobody recorded. NULL IS NEVER READ AS 'primary'.
ALTER TABLE "LoopRunLane" ADD COLUMN "verifyRung" TEXT;
