-- PLATFORM-SIGNAL PROVENANCE — what a scan could see of GitHub, and from when.
--
-- Two enrichments a file scan structurally cannot see are folded additively into D2/D3/D4:
-- the GitHub Apps posting check suites on the scored commit (review/CI/coverage tooling that is
-- INSTALLED rather than committed) and default-branch Actions health. A scan run from a worktree —
-- which is every rescan the improvement loop performs — observes neither.
--
-- Until now that difference was recorded nowhere, so it behaved as a silent ceiling: the loop scored
-- three dimensions at their file-scan floor while `green` (src/lib/maturity/green.ts) demanded L5 on
-- every dimension, making a fleet un-greenable from inside the loop for a reason nothing rendered
-- and no amount of real work could fix.
--
-- The column carries a PlatformSignalRecord: `observed` (this scan read them), `carried` (replayed
-- from an earlier observed scan, with that scan's id and age, and a `stale` marker past
-- PLATFORM_FOLD_STALE_DAYS), or `unavailable` (could not observe, nothing to carry — the dimensions
-- are excluded from the green verdict rather than counted as failed).
--
-- Additive and nullable. A NULL is UNKNOWN, which is deliberately NOT "unavailable": that reading
-- drops dimensions out of a verdict, and no historical row is entitled to make it.
ALTER TABLE "Scan" ADD COLUMN "platformSignalsJson" TEXT;
