// The `.ai/manifest.yaml` generator — the spine of the standard. Maps a ScanReport to a structured
// ManifestData, then serializes it as YAML (a human/diff-friendly VIEW of the object; the object is
// the contract). Pure and deterministic. See docs/AI_MANIFEST_SPEC.md for the versioned contract.

import type { ScanReport } from "@/lib/types";
import { commandsFor, type LangCommands } from "@/lib/practice-artifact";
import { type GeneratedFile, type ManifestData, MANIFEST_SCHEMA_VERSION } from "./types";

const SPEC_PATH = "docs/AI_MANIFEST_SPEC.md";

/** Language-manifest file a repo's commands derive from — the doctor drift-checks it. */
const SOURCE_FILE: Record<LangCommands["ci"], string> = {
  node: "package.json",
  python: "pyproject.toml",
  go: "go.mod",
  rust: "Cargo.toml",
  generic: "<your build manifest>",
};

/** Typecheck isn't in commandsFor (which is build/test/lint/install); map it per language family. */
const TYPECHECK: Record<LangCommands["ci"], string | null> = {
  node: "npx tsc --noEmit",
  python: "mypy .",
  go: "go vet ./...",
  rust: "cargo check",
  generic: null,
};

export function buildManifestData(report: ScanReport): ManifestData {
  const cmd = commandsFor(report.repo.primaryLanguage);
  const typecheck = TYPECHECK[cmd.ci];

  const capabilities: ManifestData["capabilities"] = {
    build: { command: cmd.build, verified: false },
    test: { command: cmd.test, verified: false },
    lint: { command: cmd.lint, verified: false },
  };
  if (typecheck) capabilities.typecheck = { command: typecheck, verified: false };

  return {
    schema: "ai-manifest",
    schemaVersion: MANIFEST_SCHEMA_VERSION,
    spec: SPEC_PATH,
    generatedAt: report.scannedAt.slice(0, 10),
    generatedFrom: [SOURCE_FILE[cmd.ci]],
    repo: {
      name: report.repo.name,
      purpose: report.repo.description?.trim() || "TODO: one line on what this repo is for",
      languages: report.repo.primaryLanguage ? [report.repo.primaryLanguage.toLowerCase()] : [],
      archetype: report.archetype,
    },
    capabilities,
    paths: {
      contextIndex: ".ai/context-index.json",
      memory: ".ai/memory/",
      evals: "evals/",
      guardrails: ".ai/guardrails.yaml",
    },
    context: { rule: "every module directory over 12 files has a CONTEXT.md" },
    boundaries: {
      neverTouch: [], // TODO: generated/vendored paths the agent must not hand-edit
      secretsFrom: "TODO: where secrets legitimately come from (a vault/keyring name)",
    },
    agents: [], // TODO: register any coding agents (id/kind/entrypoint), vendor-neutral
    // Recommended shift-left placement — fast checks pre-push, slow/clean-room ones in CI. The agent
    // still runs tests in its verify step regardless of where the GATE lives; this is about gates.
    // TUNE per repo: a small test suite can move to prePush; a huge one stays in CI. The doctor
    // reports which prePush controls lack a backing capability or aren't wired into the local hook.
    controls: {
      prePush: ["lint", "typecheck", "scan-secrets"],
      ciHardPass: ["test", "sast", "merge-gate"],
    },
  };
}

// ---- YAML serialization (a regular, regex-friendly subset the doctor can read zero-dep) ---------

/** Quote a scalar only when needed, so simple tokens stay clean and diff-friendly. */
function scalar(v: string): string {
  return /^[\w./@-]+$/.test(v) ? v : JSON.stringify(v);
}

function flowList(items: string[]): string {
  return `[${items.map(scalar).join(", ")}]`;
}

export function serializeManifestYaml(d: ManifestData): string {
  const caps = Object.entries(d.capabilities)
    .map(([name, c]) => `  ${name}: { command: ${JSON.stringify(c.command)}, verified: ${c.verified} }`)
    .join("\n");
  const agents = d.agents.length
    ? d.agents
        .map((a) => `  - { id: ${scalar(a.id)}, kind: ${scalar(a.kind)}, entrypoint: ${JSON.stringify(a.entrypoint)} }`)
        .join("\n")
    : "  [] # TODO: register coding agents (id/kind/entrypoint) — vendor-neutral";

  return `# .ai/manifest.yaml — the agent-facing contract for this repo.
# Generated by Ascent. Capabilities are tool-NEUTRAL (a name -> the command that fulfils it), the
# heavy subsystems are referenced by path, and unknown fields MUST be ignored — so this survives
# tool churn and schema growth. Full contract: ${d.spec}
schema: ${d.schema}
schemaVersion: ${d.schemaVersion}
spec: ${scalar(d.spec)}
generatedAt: ${JSON.stringify(d.generatedAt)}
generatedFrom: ${flowList(d.generatedFrom)}

repo:
  name: ${scalar(d.repo.name)}
  purpose: ${JSON.stringify(d.repo.purpose)}
  languages: ${flowList(d.repo.languages)}
  archetype: ${scalar(d.repo.archetype)}

# Capabilities, not tools. Add keys freely; older readers ignore unknown ones.
# \`verified\` is a claim the doctor flips to true once it has actually run the command.
capabilities:
${caps}

# Pointers — these subsystems can change format underneath without breaking this contract.
paths:
  contextIndex: ${scalar(d.paths.contextIndex)}
  memory: ${scalar(d.paths.memory)}
  evals: ${scalar(d.paths.evals)}
  guardrails: ${scalar(d.paths.guardrails)}

context:
  rule: ${JSON.stringify(d.context.rule)}

boundaries:
  neverTouch: ${flowList(d.boundaries.neverTouch)}
  secretsFrom: ${JSON.stringify(d.boundaries.secretsFrom)}

agents:
${agents}

# The control model (shift-left): where each capability is PRIMARILY enforced. CI is the thin
# backstop for hard passes only. TUNE this split for your repo — fast checks pre-push; slow suites
# (full tests, full-tree SAST) in CI. The agent runs tests in its verify step regardless of placement.
controls:
  prePush: ${flowList(d.controls.prePush)}
  ciHardPass: ${flowList(d.controls.ciHardPass)}
`;
}

export function buildManifest(report: ScanReport): GeneratedFile {
  return {
    path: ".ai/manifest.yaml",
    body: serializeManifestYaml(buildManifestData(report)),
    purpose: "The agent-facing contract: capabilities, pointers, boundaries, control placement.",
    lang: "yaml",
  };
}
