// Pins the load-bearing data-loss guard in openDraftPr (write.ts:75-88, :100-105): when a real file
// ALREADY EXISTS on the BASE branch, openDraftPr must REFUSE — throw AppApiError(409) and issue ZERO
// contents PUTs — rather than seed a TODO starter artifact over it. Merging such a PR would DELETE the
// customer's real SECURITY.md / ci.yml / AGENTS.md, and /api/practices/apply-batch fans that across up
// to 25 repos from one click. The guard is documented only by an 8-line comment; this is the only thing
// that asserts the behavior so a refactor (reorder PUT-before-check, widen the 404 swallow, or check
// `branch` instead of `base`) can't silently regress it.
//
// We mock githubAppFetch (route by GitHub API path + method) but keep the REAL AppApiError class so the
// `instanceof AppApiError` branches inside write.ts (404→null, 422 tolerance) still fire correctly.

import { describe, it, expect, vi, beforeEach } from "vitest";

const { AppApiError } = await vi.importActual<typeof import("@/lib/github/app")>("@/lib/github/app");

vi.mock("@/lib/github/app", async () => {
  const actual = await vi.importActual<typeof import("@/lib/github/app")>("@/lib/github/app");
  return {
    ...actual, // keep the real AppApiError so write.ts's instanceof checks work
    githubAppFetch: vi.fn(),
  };
});

import { openDraftPr } from "./write";
import { upsertStickyComment } from "./checks";
import { githubAppFetch } from "@/lib/github/app";

const mockFetch = vi.mocked(githubAppFetch);

const OWNER = "acme";
const REPO = "app";
const BASE = "main";
const BRANCH = "ascent/seed-security";
const FILE_PATH = "SECURITY.md";

interface Call {
  path: string;
  method: string;
  body: Record<string, unknown> | null;
}

/** Record of all calls the router observed, in order. */
let calls: Call[];

/** Returns just the contents-API PUT calls — these are the writes the guard must prevent. */
const contentPuts = () => calls.filter((c) => c.method === "PUT" && c.path.includes("/contents/"));

const baseInput = () => ({
  token: "installation-token",
  owner: OWNER,
  repo: REPO,
  branch: BRANCH,
  base: BASE,
  path: FILE_PATH,
  content: "# TODO starter artifact\n",
  commitMessage: "seed security policy",
  prTitle: "Add SECURITY.md",
  prBody: "Generated by Ascent",
});

/**
 * Build a fake githubAppFetch that routes by path/method. `state` controls the two questions the
 * guard depends on: does the file exist on BASE, and does it exist on the generated BRANCH.
 */
function installRouter(state: {
  baseFileSha?: string | null; // sha of FILE_PATH on BASE, or null/undefined = 404 (absent)
  branchFileSha?: string | null; // sha of FILE_PATH on BRANCH, or null/undefined = 404 (absent)
  branchCreate?: "ok" | "422"; // POST git/refs outcome
  prCreate?: "ok" | "422"; // POST pulls outcome
  openPrs?: { html_url: string; number: number }[]; // returned when PR-create 422s
}) {
  mockFetch.mockImplementation(async (path: string, _auth: string, init: RequestInit = {}) => {
    const method = (init.method ?? "GET").toUpperCase();
    let body: Record<string, unknown> | null = null;
    try {
      body = init.body ? (JSON.parse(init.body as string) as Record<string, unknown>) : null;
    } catch {
      body = null;
    }
    calls.push({ path, method, body });

    // resolveBaseBranch: GET /repos/owner/repo
    if (method === "GET" && path === `/repos/${OWNER}/${REPO}`) {
      return { default_branch: BASE } as never;
    }
    // refSha: GET .../git/ref/heads/<base>
    if (method === "GET" && path.includes("/git/ref/heads/")) {
      return { object: { sha: "base-sha-0001" } } as never;
    }
    // existingFileSha: GET .../contents/<path>?ref=<branch-or-base>
    if (method === "GET" && path.includes("/contents/")) {
      const ref = decodeURIComponent(path.split("?ref=")[1] ?? "");
      const sha = ref === BASE ? state.baseFileSha : state.branchFileSha;
      if (sha == null) throw new AppApiError(404, path, "Not Found");
      return { sha } as never;
    }
    // branch create: POST .../git/refs
    if (method === "POST" && path.endsWith("/git/refs")) {
      if (state.branchCreate === "422") throw new AppApiError(422, path, "Reference already exists");
      return {} as never;
    }
    // create-or-update file: PUT .../contents/<path>
    if (method === "PUT" && path.includes("/contents/")) {
      return {} as never;
    }
    // PR create: POST .../pulls
    if (method === "POST" && path.endsWith("/pulls")) {
      if (state.prCreate === "422") throw new AppApiError(422, path, "A pull request already exists");
      return { html_url: "https://github.com/acme/app/pull/7", number: 7 } as never;
    }
    // list open PRs for head: GET .../pulls?head=...&state=open
    if (method === "GET" && path.includes("/pulls?head=")) {
      return (state.openPrs ?? []) as never;
    }
    throw new Error(`unrouted call: ${method} ${path}`);
  });
}

beforeEach(() => {
  calls = [];
  mockFetch.mockReset();
});

describe("openDraftPr — never overwrite a real file on the base branch (data-loss guard)", () => {
  // (a) THE load-bearing invariant: base-file-present ⇒ 409 AND zero contents PUTs.
  it("refuses with AppApiError(409) and issues ZERO contents PUTs when the file already exists on base", async () => {
    installRouter({ baseFileSha: "real-customer-security-md-sha" });

    let thrown: unknown;
    try {
      await openDraftPr(baseInput());
    } catch (err) {
      thrown = err;
    }

    // It must throw the typed 409 so the route can map it to a friendly "won't overwrite" message...
    expect(thrown).toBeInstanceOf(AppApiError);
    expect((thrown as InstanceType<typeof AppApiError>).status).toBe(409);
    // ...and CRITICALLY: not a single create-or-update PUT may have reached the contents API.
    // (A regression that PUTs before checking base, or checks branch instead of base, fails here.)
    expect(contentPuts()).toHaveLength(0);
  });

  it("does NOT misreport success: the 409 is a thrown error, never a returned OpenPrResult", async () => {
    installRouter({ baseFileSha: "real-sha" });
    await expect(openDraftPr(baseInput())).rejects.toMatchObject({
      name: "AppApiError",
      status: 409,
    });
  });

  it("checks BASE specifically — a file present only on our generated branch does NOT trigger the guard", async () => {
    // File absent on base (404), but present on the branch from a prior run: must NOT 409.
    installRouter({ baseFileSha: null, branchFileSha: "branch-sha-from-prior-run" });
    const res = await openDraftPr(baseInput());
    expect(res.number).toBe(7);
  });
});

describe("openDraftPr — happy path creates the file on the working branch", () => {
  it("creates the file on the WORKING branch (not base) when it does not exist anywhere", async () => {
    installRouter({ baseFileSha: null, branchFileSha: null });

    const res = await openDraftPr(baseInput());

    expect(res).toMatchObject({ url: "https://github.com/acme/app/pull/7", number: 7, branch: BRANCH, reused: false });

    // Exactly one contents PUT, and it targets the working BRANCH — never base.
    const puts = contentPuts();
    expect(puts).toHaveLength(1);
    expect(puts[0].body?.branch).toBe(BRANCH);
    expect(puts[0].body?.branch).not.toBe(BASE);
    // New file ⇒ no existing sha in the PUT body (a create, not an overwrite).
    expect(puts[0].body).not.toHaveProperty("sha");

    // The PR is opened FROM the working branch INTO base, as a draft.
    const prCreate = calls.find((c) => c.method === "POST" && c.path.endsWith("/pulls"));
    expect(prCreate?.body).toMatchObject({ head: BRANCH, base: BASE, draft: true });
  });

  it("idempotent re-seed: a file present only on the branch is UPDATED with its branch sha (still not base)", async () => {
    installRouter({ baseFileSha: null, branchFileSha: "branch-existing-sha" });

    await openDraftPr(baseInput());

    const puts = contentPuts();
    expect(puts).toHaveLength(1);
    expect(puts[0].body?.branch).toBe(BRANCH);
    // Updating the branch copy carries the branch sha — and only because base was clean (404).
    expect(puts[0].body?.sha).toBe("branch-existing-sha");
  });
});

describe("openDraftPr — retry/idempotency signals", () => {
  it("tolerates a 422 on branch-create (reuses the existing branch) and still completes", async () => {
    installRouter({ baseFileSha: null, branchFileSha: null, branchCreate: "422" });
    const res = await openDraftPr(baseInput());
    expect(res.number).toBe(7);
    expect(contentPuts()).toHaveLength(1); // the write still happens on the reused branch
  });

  it("returns the already-open PR with reused:true when PR-create 422s", async () => {
    installRouter({
      baseFileSha: null,
      branchFileSha: null,
      prCreate: "422",
      openPrs: [{ html_url: "https://github.com/acme/app/pull/3", number: 3 }],
    });
    const res = await openDraftPr(baseInput());
    expect(res).toMatchObject({ url: "https://github.com/acme/app/pull/3", number: 3, reused: true });
  });
});

// ---------------------------------------------------------------------------------------------------
// upsertStickyComment (checks.ts) — find-or-create + 404-recreate. Same module/test file because it
// shares the SAME mocked githubAppFetch + REAL AppApiError surface (the 404→fall-through branch is an
// `instanceof AppApiError` check, so the real class is load-bearing). The sticky comment is the bot's
// single in-place verdict on a PR; a regression either STACKS a duplicate every sync, or THROWS when a
// race-deleted comment 404s the PATCH and kills the whole PR write. These pin find-vs-create-vs-404.
// ---------------------------------------------------------------------------------------------------

const PR_NUMBER = 42;
const MARKER = "<!-- ascent-maturity-gate -->";
// A real caller embeds the marker in the body so the NEXT run can find this same comment again.
const STICKY_BODY = `${MARKER}\n## Maturity gate: PASS\nScore 82/100`;

const stickyInput = () => ({
  token: "installation-token",
  owner: OWNER,
  repo: REPO,
  prNumber: PR_NUMBER,
  marker: MARKER,
  body: STICKY_BODY,
});

const commentPatches = () => calls.filter((c) => c.method === "PATCH" && c.path.includes("/issues/comments/"));
const commentPosts = () =>
  calls.filter((c) => c.method === "POST" && c.path.endsWith(`/issues/${PR_NUMBER}/comments`));

/**
 * Router for the comments API. `pages` is the sequence of list-pages githubAppFetch returns for the
 * GET .../issues/{n}/comments?page=… loop; `patch` controls the PATCH outcome (ok / a deleted-comment
 * 404 / some other error). PATCH/POST echo the marker'd body back as html_url-bearing JSON.
 */
function installCommentRouter(state: {
  pages: { id: number; body: string }[][]; // one entry per page returned by the search loop
  patch?: "ok" | "404" | "500"; // outcome of the PATCH to an existing comment
}) {
  mockFetch.mockImplementation(async (path: string, _auth: string, init: RequestInit = {}) => {
    const method = (init.method ?? "GET").toUpperCase();
    let body: Record<string, unknown> | null = null;
    try {
      body = init.body ? (JSON.parse(init.body as string) as Record<string, unknown>) : null;
    } catch {
      body = null;
    }
    calls.push({ path, method, body });

    // search loop: GET .../issues/{n}/comments?per_page=100&page=K
    // (match `&page=` specifically — `page=` alone also hits the `per_page=` substring).
    if (method === "GET" && path.includes(`/issues/${PR_NUMBER}/comments`)) {
      const page = Number(path.split("&page=")[1] ?? "1");
      return (state.pages[page - 1] ?? []) as never;
    }
    // update existing: PATCH .../issues/comments/{id}
    if (method === "PATCH" && path.includes("/issues/comments/")) {
      if (state.patch === "404") throw new AppApiError(404, path, "Not Found");
      if (state.patch === "500") throw new AppApiError(500, path, "Server Error");
      return { html_url: "https://github.com/acme/app/pull/42#issuecomment-111" } as never;
    }
    // create new: POST .../issues/{n}/comments
    if (method === "POST" && path.endsWith(`/issues/${PR_NUMBER}/comments`)) {
      return { html_url: "https://github.com/acme/app/pull/42#issuecomment-999" } as never;
    }
    throw new Error(`unrouted call: ${method} ${path}`);
  });
}

describe("upsertStickyComment — find-or-create + 404-recreate (one in-place comment, never stacked)", () => {
  it("FINDS a prior comment by its marker and UPDATES it in place: exactly one PATCH, zero POST, updated:true", async () => {
    installCommentRouter({
      pages: [[{ id: 7, body: "lgtm" }, { id: 8, body: `${MARKER}\n## old verdict` }]],
      patch: "ok",
    });

    const res = await upsertStickyComment(stickyInput());

    expect(res).toEqual({ url: "https://github.com/acme/app/pull/42#issuecomment-111", updated: true });
    // The match is keyed on the marker → it must PATCH that exact comment id, once, and never POST a dup.
    const patches = commentPatches();
    expect(patches).toHaveLength(1);
    expect(patches[0].path).toContain("/issues/comments/8");
    expect(commentPosts()).toHaveLength(0);
    // Marker preserved in the written body so the NEXT run finds this same comment again.
    expect(patches[0].body?.body).toContain(MARKER);
  });

  it("CREATES a new comment (POST) when no prior comment matches the marker: zero PATCH, updated:false, marker carried", async () => {
    installCommentRouter({
      pages: [[{ id: 1, body: "ci passed" }, { id: 2, body: "needs review" }]],
    });

    const res = await upsertStickyComment(stickyInput());

    expect(res).toEqual({ url: "https://github.com/acme/app/pull/42#issuecomment-999", updated: false });
    expect(commentPatches()).toHaveLength(0);
    const posts = commentPosts();
    expect(posts).toHaveLength(1);
    // The marker must be in the created body, otherwise the next sync can't find-and-update it.
    expect(posts[0].body?.body).toContain(MARKER);
  });

  it("404 on the PATCH (comment was deleted between read and write) FALLS BACK to a create instead of throwing", async () => {
    installCommentRouter({
      pages: [[{ id: 8, body: `${MARKER}\nstale` }]],
      patch: "404",
    });

    const res = await upsertStickyComment(stickyInput());

    // It tried the in-place PATCH, ate the 404, and recreated — returning the POSTed comment's url, updated:false.
    expect(res).toEqual({ url: "https://github.com/acme/app/pull/42#issuecomment-999", updated: false });
    expect(commentPatches()).toHaveLength(1); // the doomed update was attempted...
    expect(commentPosts()).toHaveLength(1); // ...then recovery created a fresh sticky comment
  });

  it("a non-404 PATCH failure RE-THROWS (does not silently double-post on a transient/permission error)", async () => {
    installCommentRouter({
      pages: [[{ id: 8, body: `${MARKER}\nstale` }]],
      patch: "500",
    });

    await expect(upsertStickyComment(stickyInput())).rejects.toMatchObject({
      name: "AppApiError",
      status: 500,
    });
    // Critically: no fallback POST on a 500 — only a 404 means "deleted, safe to recreate".
    expect(commentPosts()).toHaveLength(0);
  });

  it("matches a marker found on a LATER page (paginated search), still a single PATCH", async () => {
    // Page 1 is full (100 comments) with no match → loop continues to page 2 where the marker lives.
    const fullFirstPage = Array.from({ length: 100 }, (_, i) => ({ id: i + 1, body: `noise ${i}` }));
    installCommentRouter({
      pages: [fullFirstPage, [{ id: 808, body: `${MARKER}\non page two` }]],
      patch: "ok",
    });

    const res = await upsertStickyComment(stickyInput());

    expect(res.updated).toBe(true);
    const patches = commentPatches();
    expect(patches).toHaveLength(1);
    expect(patches[0].path).toContain("/issues/comments/808");
    expect(commentPosts()).toHaveLength(0);
  });
});
