// Pins the load-bearing data-loss guard in openDraftPr (write.ts:75-88, :100-105): when a real file
// ALREADY EXISTS on the BASE branch, openDraftPr must REFUSE — throw AppApiError(409) and issue ZERO
// contents PUTs — rather than seed a TODO starter artifact over it. Merging such a PR would DELETE the
// customer's real SECURITY.md / ci.yml / AGENTS.md, and /api/practices/apply-batch fans that across up
// to 25 repos from one click. The guard is documented only by an 8-line comment; this is the only thing
// that asserts the behavior so a refactor (reorder PUT-before-check, widen the 404 swallow, or check
// `branch` instead of `base`) can't silently regress it.
//
// We mock githubAppFetch (route by GitHub API path + method) but keep the REAL AppApiError class so the
// `instanceof AppApiError` branches inside write.ts (404→null, 422 tolerance) still fire correctly.

import { describe, it, expect, vi, beforeEach } from "vitest";

const { AppApiError } = await vi.importActual<typeof import("@/lib/github/app")>("@/lib/github/app");

vi.mock("@/lib/github/app", async () => {
  const actual = await vi.importActual<typeof import("@/lib/github/app")>("@/lib/github/app");
  return {
    ...actual, // keep the real AppApiError so write.ts's instanceof checks work
    githubAppFetch: vi.fn(),
  };
});

import { openDraftPr } from "./write";
import { githubAppFetch } from "@/lib/github/app";

const mockFetch = vi.mocked(githubAppFetch);

const OWNER = "acme";
const REPO = "app";
const BASE = "main";
const BRANCH = "ascent/seed-security";
const FILE_PATH = "SECURITY.md";

interface Call {
  path: string;
  method: string;
  body: Record<string, unknown> | null;
}

/** Record of all calls the router observed, in order. */
let calls: Call[];

/** Returns just the contents-API PUT calls — these are the writes the guard must prevent. */
const contentPuts = () => calls.filter((c) => c.method === "PUT" && c.path.includes("/contents/"));

const baseInput = () => ({
  token: "installation-token",
  owner: OWNER,
  repo: REPO,
  branch: BRANCH,
  base: BASE,
  path: FILE_PATH,
  content: "# TODO starter artifact\n",
  commitMessage: "seed security policy",
  prTitle: "Add SECURITY.md",
  prBody: "Generated by Ascent",
});

/**
 * Build a fake githubAppFetch that routes by path/method. `state` controls the two questions the
 * guard depends on: does the file exist on BASE, and does it exist on the generated BRANCH.
 */
function installRouter(state: {
  baseFileSha?: string | null; // sha of FILE_PATH on BASE, or null/undefined = 404 (absent)
  branchFileSha?: string | null; // sha of FILE_PATH on BRANCH, or null/undefined = 404 (absent)
  branchCreate?: "ok" | "422"; // POST git/refs outcome
  prCreate?: "ok" | "422"; // POST pulls outcome
  openPrs?: { html_url: string; number: number }[]; // returned when PR-create 422s
}) {
  mockFetch.mockImplementation(async (path: string, _auth: string, init: RequestInit = {}) => {
    const method = (init.method ?? "GET").toUpperCase();
    let body: Record<string, unknown> | null = null;
    try {
      body = init.body ? (JSON.parse(init.body as string) as Record<string, unknown>) : null;
    } catch {
      body = null;
    }
    calls.push({ path, method, body });

    // resolveBaseBranch: GET /repos/owner/repo
    if (method === "GET" && path === `/repos/${OWNER}/${REPO}`) {
      return { default_branch: BASE } as never;
    }
    // refSha: GET .../git/ref/heads/<base>
    if (method === "GET" && path.includes("/git/ref/heads/")) {
      return { object: { sha: "base-sha-0001" } } as never;
    }
    // existingFileSha: GET .../contents/<path>?ref=<branch-or-base>
    if (method === "GET" && path.includes("/contents/")) {
      const ref = decodeURIComponent(path.split("?ref=")[1] ?? "");
      const sha = ref === BASE ? state.baseFileSha : state.branchFileSha;
      if (sha == null) throw new AppApiError(404, path, "Not Found");
      return { sha } as never;
    }
    // branch create: POST .../git/refs
    if (method === "POST" && path.endsWith("/git/refs")) {
      if (state.branchCreate === "422") throw new AppApiError(422, path, "Reference already exists");
      return {} as never;
    }
    // create-or-update file: PUT .../contents/<path>
    if (method === "PUT" && path.includes("/contents/")) {
      return {} as never;
    }
    // PR create: POST .../pulls
    if (method === "POST" && path.endsWith("/pulls")) {
      if (state.prCreate === "422") throw new AppApiError(422, path, "A pull request already exists");
      return { html_url: "https://github.com/acme/app/pull/7", number: 7 } as never;
    }
    // list open PRs for head: GET .../pulls?head=...&state=open
    if (method === "GET" && path.includes("/pulls?head=")) {
      return (state.openPrs ?? []) as never;
    }
    throw new Error(`unrouted call: ${method} ${path}`);
  });
}

beforeEach(() => {
  calls = [];
  mockFetch.mockReset();
});

describe("openDraftPr — never overwrite a real file on the base branch (data-loss guard)", () => {
  // (a) THE load-bearing invariant: base-file-present ⇒ 409 AND zero contents PUTs.
  it("refuses with AppApiError(409) and issues ZERO contents PUTs when the file already exists on base", async () => {
    installRouter({ baseFileSha: "real-customer-security-md-sha" });

    let thrown: unknown;
    try {
      await openDraftPr(baseInput());
    } catch (err) {
      thrown = err;
    }

    // It must throw the typed 409 so the route can map it to a friendly "won't overwrite" message...
    expect(thrown).toBeInstanceOf(AppApiError);
    expect((thrown as InstanceType<typeof AppApiError>).status).toBe(409);
    // ...and CRITICALLY: not a single create-or-update PUT may have reached the contents API.
    // (A regression that PUTs before checking base, or checks branch instead of base, fails here.)
    expect(contentPuts()).toHaveLength(0);
  });

  it("does NOT misreport success: the 409 is a thrown error, never a returned OpenPrResult", async () => {
    installRouter({ baseFileSha: "real-sha" });
    await expect(openDraftPr(baseInput())).rejects.toMatchObject({
      name: "AppApiError",
      status: 409,
    });
  });

  it("checks BASE specifically — a file present only on our generated branch does NOT trigger the guard", async () => {
    // File absent on base (404), but present on the branch from a prior run: must NOT 409.
    installRouter({ baseFileSha: null, branchFileSha: "branch-sha-from-prior-run" });
    const res = await openDraftPr(baseInput());
    expect(res.number).toBe(7);
  });
});

describe("openDraftPr — happy path creates the file on the working branch", () => {
  it("creates the file on the WORKING branch (not base) when it does not exist anywhere", async () => {
    installRouter({ baseFileSha: null, branchFileSha: null });

    const res = await openDraftPr(baseInput());

    expect(res).toMatchObject({ url: "https://github.com/acme/app/pull/7", number: 7, branch: BRANCH, reused: false });

    // Exactly one contents PUT, and it targets the working BRANCH — never base.
    const puts = contentPuts();
    expect(puts).toHaveLength(1);
    expect(puts[0].body?.branch).toBe(BRANCH);
    expect(puts[0].body?.branch).not.toBe(BASE);
    // New file ⇒ no existing sha in the PUT body (a create, not an overwrite).
    expect(puts[0].body).not.toHaveProperty("sha");

    // The PR is opened FROM the working branch INTO base, as a draft.
    const prCreate = calls.find((c) => c.method === "POST" && c.path.endsWith("/pulls"));
    expect(prCreate?.body).toMatchObject({ head: BRANCH, base: BASE, draft: true });
  });

  it("idempotent re-seed: a file present only on the branch is UPDATED with its branch sha (still not base)", async () => {
    installRouter({ baseFileSha: null, branchFileSha: "branch-existing-sha" });

    await openDraftPr(baseInput());

    const puts = contentPuts();
    expect(puts).toHaveLength(1);
    expect(puts[0].body?.branch).toBe(BRANCH);
    // Updating the branch copy carries the branch sha — and only because base was clean (404).
    expect(puts[0].body?.sha).toBe("branch-existing-sha");
  });
});

describe("openDraftPr — retry/idempotency signals", () => {
  it("tolerates a 422 on branch-create (reuses the existing branch) and still completes", async () => {
    installRouter({ baseFileSha: null, branchFileSha: null, branchCreate: "422" });
    const res = await openDraftPr(baseInput());
    expect(res.number).toBe(7);
    expect(contentPuts()).toHaveLength(1); // the write still happens on the reused branch
  });

  it("returns the already-open PR with reused:true when PR-create 422s", async () => {
    installRouter({
      baseFileSha: null,
      branchFileSha: null,
      prCreate: "422",
      openPrs: [{ html_url: "https://github.com/acme/app/pull/3", number: 3 }],
    });
    const res = await openDraftPr(baseInput());
    expect(res).toMatchObject({ url: "https://github.com/acme/app/pull/3", number: 3, reused: true });
  });
});
