-- WHEN THE RESCAN ADJUDICATED A CLOSE — the verification stamp, written at adjudication time.
--
-- `LaneItemOutcome.verdict` holds `resolved` for two different statements: a close the RESCAN ruled
-- (the gap is no longer raised AND its dimension measurably moved, per `decideInProgress`) and a
-- close the AGENT merely claimed. The claim/verdict split (UAT `PRIYA-L1-702`) added a `verified`
-- discriminator, but DERIVED it at read time by joining the lane's `closedIdsJson` — and every lane
-- written before that fix stored the raw commit-TRAILER set there, which is the agent's own claim.
-- So the tautology re-entered through the join: a recertification sweep found 36 of 36 historical
-- rows still reading `verified: true`, and zero rendering the new "claimed resolved" label.
--
-- This column stores the fact where it happened. NULL is therefore the correct and honest value for
-- every pre-existing row: nothing adjudicated those closes, and no backfill can invent an
-- adjudication that never took place. There is deliberately NO backfill statement here.
--
-- NULL IS NEVER VERIFIED. Any code path that reads this column must treat null as unverified.
ALTER TABLE "LaneItemOutcome" ADD COLUMN "verifiedAt" TIMESTAMP(3);
